// Code generated by ent, DO NOT EDIT.

package guesttoken

import (
	"ledit/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldID, id))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldRevokedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContainsFold(FieldLabel, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotNull(FieldExpiresAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotNull(FieldRevokedAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.GuestToken {
	return predicate.GuestToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.GuestToken {
	return predicate.GuestToken(sql.FieldNotNull(FieldLastUsedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GuestToken) predicate.GuestToken {
	return predicate.GuestToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GuestToken) predicate.GuestToken {
	return predicate.GuestToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GuestToken) predicate.GuestToken {
	return predicate.GuestToken(sql.NotPredicates(p))
}
