// Code generated by ent, DO NOT EDIT.

package sports

import (
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldID, id))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldToken, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldURL, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldConfig, v))
}

// LiveRefreshSeconds applies equality check predicate on the "live_refresh_seconds" field. It's identical to LiveRefreshSecondsEQ.
func LiveRefreshSeconds(v int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldLiveRefreshSeconds, v))
}

// IdleRefreshSeconds applies equality check predicate on the "idle_refresh_seconds" field. It's identical to IdleRefreshSecondsEQ.
func IdleRefreshSeconds(v int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldIdleRefreshSeconds, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContainsFold(FieldToken, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContainsFold(FieldURL, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldProvider, vs...))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.Sports {
	return predicate.Sports(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.Sports {
	return predicate.Sports(sql.FieldContainsFold(FieldConfig, v))
}

// LiveRefreshSecondsEQ applies the EQ predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsEQ(v int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldLiveRefreshSeconds, v))
}

// LiveRefreshSecondsNEQ applies the NEQ predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsNEQ(v int) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldLiveRefreshSeconds, v))
}

// LiveRefreshSecondsIn applies the In predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsIn(vs ...int) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldLiveRefreshSeconds, vs...))
}

// LiveRefreshSecondsNotIn applies the NotIn predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsNotIn(vs ...int) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldLiveRefreshSeconds, vs...))
}

// LiveRefreshSecondsGT applies the GT predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsGT(v int) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldLiveRefreshSeconds, v))
}

// LiveRefreshSecondsGTE applies the GTE predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsGTE(v int) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldLiveRefreshSeconds, v))
}

// LiveRefreshSecondsLT applies the LT predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsLT(v int) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldLiveRefreshSeconds, v))
}

// LiveRefreshSecondsLTE applies the LTE predicate on the "live_refresh_seconds" field.
func LiveRefreshSecondsLTE(v int) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldLiveRefreshSeconds, v))
}

// IdleRefreshSecondsEQ applies the EQ predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsEQ(v int) predicate.Sports {
	return predicate.Sports(sql.FieldEQ(FieldIdleRefreshSeconds, v))
}

// IdleRefreshSecondsNEQ applies the NEQ predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsNEQ(v int) predicate.Sports {
	return predicate.Sports(sql.FieldNEQ(FieldIdleRefreshSeconds, v))
}

// IdleRefreshSecondsIn applies the In predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsIn(vs ...int) predicate.Sports {
	return predicate.Sports(sql.FieldIn(FieldIdleRefreshSeconds, vs...))
}

// IdleRefreshSecondsNotIn applies the NotIn predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsNotIn(vs ...int) predicate.Sports {
	return predicate.Sports(sql.FieldNotIn(FieldIdleRefreshSeconds, vs...))
}

// IdleRefreshSecondsGT applies the GT predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsGT(v int) predicate.Sports {
	return predicate.Sports(sql.FieldGT(FieldIdleRefreshSeconds, v))
}

// IdleRefreshSecondsGTE applies the GTE predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsGTE(v int) predicate.Sports {
	return predicate.Sports(sql.FieldGTE(FieldIdleRefreshSeconds, v))
}

// IdleRefreshSecondsLT applies the LT predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsLT(v int) predicate.Sports {
	return predicate.Sports(sql.FieldLT(FieldIdleRefreshSeconds, v))
}

// IdleRefreshSecondsLTE applies the LTE predicate on the "idle_refresh_seconds" field.
func IdleRefreshSecondsLTE(v int) predicate.Sports {
	return predicate.Sports(sql.FieldLTE(FieldIdleRefreshSeconds, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sports) predicate.Sports {
	return predicate.Sports(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sports) predicate.Sports {
	return predicate.Sports(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sports) predicate.Sports {
	return predicate.Sports(sql.NotPredicates(p))
}
