// Code generated by ent, DO NOT EDIT.

package devicesettings

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the devicesettings type in the database.
	Label = "device_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldRefreshInterval holds the string denoting the refresh_interval field in the database.
	FieldRefreshInterval = "refresh_interval"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldFramesServed holds the string denoting the frames_served field in the database.
	FieldFramesServed = "frames_served"
	// FieldContentMode holds the string denoting the content_mode field in the database.
	FieldContentMode = "content_mode"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"
	// Table holds the table name of the devicesettings in the database.
	Table = "device_settings"
)

// Columns holds all SQL columns for devicesettings fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIP,
	FieldPort,
	FieldUsername,
	FieldPassword,
	FieldWidth,
	FieldHeight,
	FieldEnabled,
	FieldToken,
	FieldRefreshInterval,
	FieldLastSeenAt,
	FieldFramesServed,
	FieldContentMode,
	FieldPlaylistID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "device_settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"general_settings_device_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultIP holds the default value on creation for the "ip" field.
	DefaultIP string
	// DefaultPort holds the default value on creation for the "port" field.
	DefaultPort int
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultPassword holds the default value on creation for the "password" field.
	DefaultPassword string
	// DefaultWidth holds the default value on creation for the "width" field.
	DefaultWidth int
	// DefaultHeight holds the default value on creation for the "height" field.
	DefaultHeight int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultRefreshInterval holds the default value on creation for the "refresh_interval" field.
	DefaultRefreshInterval int
	// DefaultFramesServed holds the default value on creation for the "frames_served" field.
	DefaultFramesServed int
	// DefaultContentMode holds the default value on creation for the "content_mode" field.
	DefaultContentMode string
	// ContentModeValidator is a validator for the "content_mode" field. It is called by the builders before save.
	ContentModeValidator func(string) error
)

// OrderOption defines the ordering options for the DeviceSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByRefreshInterval orders the results by the refresh_interval field.
func ByRefreshInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshInterval, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByFramesServed orders the results by the frames_served field.
func ByFramesServed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFramesServed, opts...).ToFunc()
}

// ByContentMode orders the results by the content_mode field.
func ByContentMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentMode, opts...).ToFunc()
}

// ByPlaylistID orders the results by the playlist_id field.
func ByPlaylistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaylistID, opts...).ToFunc()
}
