// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/adminsettings"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AdminSettings is the model entity for the AdminSettings schema.
type AdminSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminsettings.FieldID:
			values[i] = new(sql.NullInt64)
		case adminsettings.FieldUsername, adminsettings.FieldPasswordHash:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminSettings fields.
func (_m *AdminSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminsettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case adminsettings.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case adminsettings.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminSettings.
// This includes values selected through modifiers, order, etc.
func (_m *AdminSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AdminSettings.
// Note that you need to call AdminSettings.Unwrap() before calling this method if this AdminSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminSettings) Update() *AdminSettingsUpdateOne {
	return NewAdminSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminSettings) Unwrap() *AdminSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminSettings) String() string {
	var builder strings.Builder
	builder.WriteString("AdminSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteByte(')')
	return builder.String()
}

// AdminSettingsSlice is a parsable slice of AdminSettings.
type AdminSettingsSlice []*AdminSettings
