// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ledit/ent/airquality"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AirQualityDelete is the builder for deleting a AirQuality entity.
type AirQualityDelete struct {
	config
	hooks    []Hook
	mutation *AirQualityMutation
}

// Where appends a list predicates to the AirQualityDelete builder.
func (_d *AirQualityDelete) Where(ps ...predicate.AirQuality) *AirQualityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AirQualityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AirQualityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AirQualityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(airquality.Table, sqlgraph.NewFieldSpec(airquality.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AirQualityDeleteOne is the builder for deleting a single AirQuality entity.
type AirQualityDeleteOne struct {
	_d *AirQualityDelete
}

// Where appends a list predicates to the AirQualityDelete builder.
func (_d *AirQualityDeleteOne) Where(ps ...predicate.AirQuality) *AirQualityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AirQualityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{airquality.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AirQualityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
