// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/aisettings"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AISettingsUpdate is the builder for updating AISettings entities.
type AISettingsUpdate struct {
	config
	hooks    []Hook
	mutation *AISettingsMutation
}

// Where appends a list predicates to the AISettingsUpdate builder.
func (_u *AISettingsUpdate) Where(ps ...predicate.AISettings) *AISettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AISettingsUpdate) SetProvider(v string) *AISettingsUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AISettingsUpdate) SetNillableProvider(v *string) *AISettingsUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AISettingsUpdate) SetAPIKey(v string) *AISettingsUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AISettingsUpdate) SetNillableAPIKey(v *string) *AISettingsUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AISettingsUpdate) SetModel(v string) *AISettingsUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AISettingsUpdate) SetNillableModel(v *string) *AISettingsUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *AISettingsUpdate) SetEndpoint(v string) *AISettingsUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *AISettingsUpdate) SetNillableEndpoint(v *string) *AISettingsUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *AISettingsUpdate) ClearEndpoint() *AISettingsUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// Mutation returns the AISettingsMutation object of the builder.
func (_u *AISettingsUpdate) Mutation() *AISettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AISettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AISettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AISettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AISettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AISettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(aisettings.Table, aisettings.Columns, sqlgraph.NewFieldSpec(aisettings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(aisettings.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aisettings.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aisettings.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(aisettings.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(aisettings.FieldEndpoint, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aisettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AISettingsUpdateOne is the builder for updating a single AISettings entity.
type AISettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AISettingsMutation
}

// SetProvider sets the "provider" field.
func (_u *AISettingsUpdateOne) SetProvider(v string) *AISettingsUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AISettingsUpdateOne) SetNillableProvider(v *string) *AISettingsUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AISettingsUpdateOne) SetAPIKey(v string) *AISettingsUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AISettingsUpdateOne) SetNillableAPIKey(v *string) *AISettingsUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AISettingsUpdateOne) SetModel(v string) *AISettingsUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AISettingsUpdateOne) SetNillableModel(v *string) *AISettingsUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *AISettingsUpdateOne) SetEndpoint(v string) *AISettingsUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *AISettingsUpdateOne) SetNillableEndpoint(v *string) *AISettingsUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *AISettingsUpdateOne) ClearEndpoint() *AISettingsUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// Mutation returns the AISettingsMutation object of the builder.
func (_u *AISettingsUpdateOne) Mutation() *AISettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the AISettingsUpdate builder.
func (_u *AISettingsUpdateOne) Where(ps ...predicate.AISettings) *AISettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AISettingsUpdateOne) Select(field string, fields ...string) *AISettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AISettings entity.
func (_u *AISettingsUpdateOne) Save(ctx context.Context) (*AISettings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AISettingsUpdateOne) SaveX(ctx context.Context) *AISettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AISettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AISettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AISettingsUpdateOne) sqlSave(ctx context.Context) (_node *AISettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(aisettings.Table, aisettings.Columns, sqlgraph.NewFieldSpec(aisettings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AISettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aisettings.FieldID)
		for _, f := range fields {
			if !aisettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aisettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(aisettings.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aisettings.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aisettings.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(aisettings.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(aisettings.FieldEndpoint, field.TypeString)
	}
	_node = &AISettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aisettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
