// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/chartsample"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ChartSample is the model entity for the ChartSample schema.
type ChartSample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// SampledAt holds the value of the "sampled_at" field.
	SampledAt time.Time `json:"sampled_at,omitempty"`
	// Value holds the value of the "value" field.
	Value float64 `json:"value,omitempty"`
	// Open holds the value of the "open" field.
	Open *float64 `json:"open,omitempty"`
	// High holds the value of the "high" field.
	High *float64 `json:"high,omitempty"`
	// Low holds the value of the "low" field.
	Low *float64 `json:"low,omitempty"`
	// Close holds the value of the "close" field.
	Close *float64 `json:"close,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChartSample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chartsample.FieldValue, chartsample.FieldOpen, chartsample.FieldHigh, chartsample.FieldLow, chartsample.FieldClose:
			values[i] = new(sql.NullFloat64)
		case chartsample.FieldID:
			values[i] = new(sql.NullInt64)
		case chartsample.FieldSourceType, chartsample.FieldSourceID:
			values[i] = new(sql.NullString)
		case chartsample.FieldSampledAt, chartsample.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChartSample fields.
func (_m *ChartSample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chartsample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chartsample.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case chartsample.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case chartsample.FieldSampledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sampled_at", values[i])
			} else if value.Valid {
				_m.SampledAt = value.Time
			}
		case chartsample.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.Float64
			}
		case chartsample.FieldOpen:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field open", values[i])
			} else if value.Valid {
				_m.Open = new(float64)
				*_m.Open = value.Float64
			}
		case chartsample.FieldHigh:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field high", values[i])
			} else if value.Valid {
				_m.High = new(float64)
				*_m.High = value.Float64
			}
		case chartsample.FieldLow:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field low", values[i])
			} else if value.Valid {
				_m.Low = new(float64)
				*_m.Low = value.Float64
			}
		case chartsample.FieldClose:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field close", values[i])
			} else if value.Valid {
				_m.Close = new(float64)
				*_m.Close = value.Float64
			}
		case chartsample.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the ChartSample.
// This includes values selected through modifiers, order, etc.
func (_m *ChartSample) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChartSample.
// Note that you need to call ChartSample.Unwrap() before calling this method if this ChartSample
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChartSample) Update() *ChartSampleUpdateOne {
	return NewChartSampleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChartSample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChartSample) Unwrap() *ChartSample {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChartSample is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChartSample) String() string {
	var builder strings.Builder
	builder.WriteString("ChartSample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("sampled_at=")
	builder.WriteString(_m.SampledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	if v := _m.Open; v != nil {
		builder.WriteString("open=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.High; v != nil {
		builder.WriteString("high=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Low; v != nil {
		builder.WriteString("low=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Close; v != nil {
		builder.WriteString("close=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChartSamples is a parsable slice of ChartSample.
type ChartSamples []*ChartSample
