// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/devicegroup"
	"ledit/ent/devicesettings"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeviceSettings is the model entity for the DeviceSettings schema.
type DeviceSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Port holds the value of the "port" field.
	Port int `json:"port,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Width holds the value of the "width" field.
	Width int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// RefreshInterval holds the value of the "refresh_interval" field.
	RefreshInterval int `json:"refresh_interval,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	// FramesServed holds the value of the "frames_served" field.
	FramesServed int `json:"frames_served,omitempty"`
	// ContentMode holds the value of the "content_mode" field.
	ContentMode string `json:"content_mode,omitempty"`
	// PlaylistID holds the value of the "playlist_id" field.
	PlaylistID *int `json:"playlist_id,omitempty"`
	// JSON: [1,2,3] ordered candidate playlist ids for scheduled mode
	ScheduledPlaylistIds string `json:"scheduled_playlist_ids,omitempty"`
	// FallbackPlaylistID holds the value of the "fallback_playlist_id" field.
	FallbackPlaylistID *int `json:"fallback_playlist_id,omitempty"`
	// BrightnessEnabled holds the value of the "brightness_enabled" field.
	BrightnessEnabled bool `json:"brightness_enabled,omitempty"`
	// JSON: [{days:[0..6], start:"HH:MM", end:"HH:MM", level:int}]
	BrightnessSchedules string `json:"brightness_schedules,omitempty"`
	// BrightnessOverride holds the value of the "brightness_override" field.
	BrightnessOverride *int `json:"brightness_override,omitempty"`
	// JSON: {entity_id:string, lux_levels:[{maxLux,float level int}]}
	BrightnessSensorConfig *string `json:"brightness_sensor_config,omitempty"`
	// IdleScreensaver holds the value of the "idle_screensaver" field.
	IdleScreensaver *string `json:"idle_screensaver,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int `json:"group_id,omitempty"`
	// OverlayEnabled holds the value of the "overlay_enabled" field.
	OverlayEnabled bool `json:"overlay_enabled,omitempty"`
	// OverlayPosition holds the value of the "overlay_position" field.
	OverlayPosition string `json:"overlay_position,omitempty"`
	// OverlayHeight holds the value of the "overlay_height" field.
	OverlayHeight int `json:"overlay_height,omitempty"`
	// OverlayText holds the value of the "overlay_text" field.
	OverlayText string `json:"overlay_text,omitempty"`
	// OverlaySpeedPx holds the value of the "overlay_speed_px" field.
	OverlaySpeedPx int `json:"overlay_speed_px,omitempty"`
	// OverlayBg holds the value of the "overlay_bg" field.
	OverlayBg string `json:"overlay_bg,omitempty"`
	// OverlayFg holds the value of the "overlay_fg" field.
	OverlayFg string `json:"overlay_fg,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceSettingsQuery when eager-loading is set.
	Edges                            DeviceSettingsEdges `json:"edges"`
	general_settings_device_settings *int
	selectValues                     sql.SelectValues
}

// DeviceSettingsEdges holds the relations/edges for other nodes in the graph.
type DeviceSettingsEdges struct {
	// Group holds the value of the group edge.
	Group *DeviceGroup `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceSettingsEdges) GroupOrErr() (*DeviceGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: devicegroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicesettings.FieldEnabled, devicesettings.FieldBrightnessEnabled, devicesettings.FieldOverlayEnabled:
			values[i] = new(sql.NullBool)
		case devicesettings.FieldID, devicesettings.FieldPort, devicesettings.FieldWidth, devicesettings.FieldHeight, devicesettings.FieldRefreshInterval, devicesettings.FieldFramesServed, devicesettings.FieldPlaylistID, devicesettings.FieldFallbackPlaylistID, devicesettings.FieldBrightnessOverride, devicesettings.FieldGroupID, devicesettings.FieldOverlayHeight, devicesettings.FieldOverlaySpeedPx:
			values[i] = new(sql.NullInt64)
		case devicesettings.FieldName, devicesettings.FieldIP, devicesettings.FieldUsername, devicesettings.FieldPassword, devicesettings.FieldToken, devicesettings.FieldContentMode, devicesettings.FieldScheduledPlaylistIds, devicesettings.FieldBrightnessSchedules, devicesettings.FieldBrightnessSensorConfig, devicesettings.FieldIdleScreensaver, devicesettings.FieldOverlayPosition, devicesettings.FieldOverlayText, devicesettings.FieldOverlayBg, devicesettings.FieldOverlayFg:
			values[i] = new(sql.NullString)
		case devicesettings.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		case devicesettings.ForeignKeys[0]: // general_settings_device_settings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceSettings fields.
func (_m *DeviceSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicesettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case devicesettings.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case devicesettings.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case devicesettings.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case devicesettings.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case devicesettings.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case devicesettings.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case devicesettings.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case devicesettings.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case devicesettings.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case devicesettings.FieldRefreshInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval", values[i])
			} else if value.Valid {
				_m.RefreshInterval = int(value.Int64)
			}
		case devicesettings.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		case devicesettings.FieldFramesServed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field frames_served", values[i])
			} else if value.Valid {
				_m.FramesServed = int(value.Int64)
			}
		case devicesettings.FieldContentMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_mode", values[i])
			} else if value.Valid {
				_m.ContentMode = value.String
			}
		case devicesettings.FieldPlaylistID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_id", values[i])
			} else if value.Valid {
				_m.PlaylistID = new(int)
				*_m.PlaylistID = int(value.Int64)
			}
		case devicesettings.FieldScheduledPlaylistIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_playlist_ids", values[i])
			} else if value.Valid {
				_m.ScheduledPlaylistIds = value.String
			}
		case devicesettings.FieldFallbackPlaylistID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_playlist_id", values[i])
			} else if value.Valid {
				_m.FallbackPlaylistID = new(int)
				*_m.FallbackPlaylistID = int(value.Int64)
			}
		case devicesettings.FieldBrightnessEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field brightness_enabled", values[i])
			} else if value.Valid {
				_m.BrightnessEnabled = value.Bool
			}
		case devicesettings.FieldBrightnessSchedules:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brightness_schedules", values[i])
			} else if value.Valid {
				_m.BrightnessSchedules = value.String
			}
		case devicesettings.FieldBrightnessOverride:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field brightness_override", values[i])
			} else if value.Valid {
				_m.BrightnessOverride = new(int)
				*_m.BrightnessOverride = int(value.Int64)
			}
		case devicesettings.FieldBrightnessSensorConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brightness_sensor_config", values[i])
			} else if value.Valid {
				_m.BrightnessSensorConfig = new(string)
				*_m.BrightnessSensorConfig = value.String
			}
		case devicesettings.FieldIdleScreensaver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idle_screensaver", values[i])
			} else if value.Valid {
				_m.IdleScreensaver = new(string)
				*_m.IdleScreensaver = value.String
			}
		case devicesettings.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int)
				*_m.GroupID = int(value.Int64)
			}
		case devicesettings.FieldOverlayEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_enabled", values[i])
			} else if value.Valid {
				_m.OverlayEnabled = value.Bool
			}
		case devicesettings.FieldOverlayPosition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_position", values[i])
			} else if value.Valid {
				_m.OverlayPosition = value.String
			}
		case devicesettings.FieldOverlayHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_height", values[i])
			} else if value.Valid {
				_m.OverlayHeight = int(value.Int64)
			}
		case devicesettings.FieldOverlayText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_text", values[i])
			} else if value.Valid {
				_m.OverlayText = value.String
			}
		case devicesettings.FieldOverlaySpeedPx:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_speed_px", values[i])
			} else if value.Valid {
				_m.OverlaySpeedPx = int(value.Int64)
			}
		case devicesettings.FieldOverlayBg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_bg", values[i])
			} else if value.Valid {
				_m.OverlayBg = value.String
			}
		case devicesettings.FieldOverlayFg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_fg", values[i])
			} else if value.Valid {
				_m.OverlayFg = value.String
			}
		case devicesettings.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field general_settings_device_settings", value)
			} else if value.Valid {
				_m.general_settings_device_settings = new(int)
				*_m.general_settings_device_settings = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceSettings.
// This includes values selected through modifiers, order, etc.
func (_m *DeviceSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the DeviceSettings entity.
func (_m *DeviceSettings) QueryGroup() *DeviceGroupQuery {
	return NewDeviceSettingsClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this DeviceSettings.
// Note that you need to call DeviceSettings.Unwrap() before calling this method if this DeviceSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeviceSettings) Update() *DeviceSettingsUpdateOne {
	return NewDeviceSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeviceSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeviceSettings) Unwrap() *DeviceSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeviceSettings) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("refresh_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshInterval))
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("frames_served=")
	builder.WriteString(fmt.Sprintf("%v", _m.FramesServed))
	builder.WriteString(", ")
	builder.WriteString("content_mode=")
	builder.WriteString(_m.ContentMode)
	builder.WriteString(", ")
	if v := _m.PlaylistID; v != nil {
		builder.WriteString("playlist_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("scheduled_playlist_ids=")
	builder.WriteString(_m.ScheduledPlaylistIds)
	builder.WriteString(", ")
	if v := _m.FallbackPlaylistID; v != nil {
		builder.WriteString("fallback_playlist_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("brightness_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.BrightnessEnabled))
	builder.WriteString(", ")
	builder.WriteString("brightness_schedules=")
	builder.WriteString(_m.BrightnessSchedules)
	builder.WriteString(", ")
	if v := _m.BrightnessOverride; v != nil {
		builder.WriteString("brightness_override=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BrightnessSensorConfig; v != nil {
		builder.WriteString("brightness_sensor_config=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdleScreensaver; v != nil {
		builder.WriteString("idle_screensaver=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("overlay_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverlayEnabled))
	builder.WriteString(", ")
	builder.WriteString("overlay_position=")
	builder.WriteString(_m.OverlayPosition)
	builder.WriteString(", ")
	builder.WriteString("overlay_height=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverlayHeight))
	builder.WriteString(", ")
	builder.WriteString("overlay_text=")
	builder.WriteString(_m.OverlayText)
	builder.WriteString(", ")
	builder.WriteString("overlay_speed_px=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverlaySpeedPx))
	builder.WriteString(", ")
	builder.WriteString("overlay_bg=")
	builder.WriteString(_m.OverlayBg)
	builder.WriteString(", ")
	builder.WriteString("overlay_fg=")
	builder.WriteString(_m.OverlayFg)
	builder.WriteByte(')')
	return builder.String()
}

// DeviceSettingsSlice is a parsable slice of DeviceSettings.
type DeviceSettingsSlice []*DeviceSettings
