// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/emailsettings"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailSettingsUpdate is the builder for updating EmailSettings entities.
type EmailSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *EmailSettingsMutation
}

// Where appends a list predicates to the EmailSettingsUpdate builder.
func (_u *EmailSettingsUpdate) Where(ps ...predicate.EmailSettings) *EmailSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHost sets the "host" field.
func (_u *EmailSettingsUpdate) SetHost(v string) *EmailSettingsUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillableHost(v *string) *EmailSettingsUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *EmailSettingsUpdate) SetPort(v int) *EmailSettingsUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillablePort(v *int) *EmailSettingsUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *EmailSettingsUpdate) AddPort(v int) *EmailSettingsUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *EmailSettingsUpdate) SetUsername(v string) *EmailSettingsUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillableUsername(v *string) *EmailSettingsUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *EmailSettingsUpdate) SetPassword(v string) *EmailSettingsUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillablePassword(v *string) *EmailSettingsUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *EmailSettingsUpdate) SetFromAddress(v string) *EmailSettingsUpdate {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillableFromAddress(v *string) *EmailSettingsUpdate {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetUseTLS sets the "use_tls" field.
func (_u *EmailSettingsUpdate) SetUseTLS(v bool) *EmailSettingsUpdate {
	_u.mutation.SetUseTLS(v)
	return _u
}

// SetNillableUseTLS sets the "use_tls" field if the given value is not nil.
func (_u *EmailSettingsUpdate) SetNillableUseTLS(v *bool) *EmailSettingsUpdate {
	if v != nil {
		_u.SetUseTLS(*v)
	}
	return _u
}

// Mutation returns the EmailSettingsMutation object of the builder.
func (_u *EmailSettingsUpdate) Mutation() *EmailSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailSettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmailSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(emailsettings.Table, emailsettings.Columns, sqlgraph.NewFieldSpec(emailsettings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(emailsettings.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(emailsettings.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(emailsettings.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(emailsettings.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(emailsettings.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(emailsettings.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UseTLS(); ok {
		_spec.SetField(emailsettings.FieldUseTLS, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailSettingsUpdateOne is the builder for updating a single EmailSettings entity.
type EmailSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailSettingsMutation
}

// SetHost sets the "host" field.
func (_u *EmailSettingsUpdateOne) SetHost(v string) *EmailSettingsUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillableHost(v *string) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *EmailSettingsUpdateOne) SetPort(v int) *EmailSettingsUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillablePort(v *int) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *EmailSettingsUpdateOne) AddPort(v int) *EmailSettingsUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *EmailSettingsUpdateOne) SetUsername(v string) *EmailSettingsUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillableUsername(v *string) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *EmailSettingsUpdateOne) SetPassword(v string) *EmailSettingsUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillablePassword(v *string) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *EmailSettingsUpdateOne) SetFromAddress(v string) *EmailSettingsUpdateOne {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillableFromAddress(v *string) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetUseTLS sets the "use_tls" field.
func (_u *EmailSettingsUpdateOne) SetUseTLS(v bool) *EmailSettingsUpdateOne {
	_u.mutation.SetUseTLS(v)
	return _u
}

// SetNillableUseTLS sets the "use_tls" field if the given value is not nil.
func (_u *EmailSettingsUpdateOne) SetNillableUseTLS(v *bool) *EmailSettingsUpdateOne {
	if v != nil {
		_u.SetUseTLS(*v)
	}
	return _u
}

// Mutation returns the EmailSettingsMutation object of the builder.
func (_u *EmailSettingsUpdateOne) Mutation() *EmailSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailSettingsUpdate builder.
func (_u *EmailSettingsUpdateOne) Where(ps ...predicate.EmailSettings) *EmailSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailSettingsUpdateOne) Select(field string, fields ...string) *EmailSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailSettings entity.
func (_u *EmailSettingsUpdateOne) Save(ctx context.Context) (*EmailSettings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSettingsUpdateOne) SaveX(ctx context.Context) *EmailSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmailSettingsUpdateOne) sqlSave(ctx context.Context) (_node *EmailSettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(emailsettings.Table, emailsettings.Columns, sqlgraph.NewFieldSpec(emailsettings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailsettings.FieldID)
		for _, f := range fields {
			if !emailsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(emailsettings.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(emailsettings.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(emailsettings.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(emailsettings.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(emailsettings.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(emailsettings.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UseTLS(); ok {
		_spec.SetField(emailsettings.FieldUseTLS, field.TypeBool, value)
	}
	_node = &EmailSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
