// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"ledit/ent/f1"
	"ledit/ent/predicate"
)

// F1Update is the builder for updating F1 entities.
type F1Update struct {
	config
	hooks    []Hook
	mutation *F1Mutation
}

// Where appends a list predicates to the F1Update builder.
func (_u *F1Update) Where(ps ...predicate.F1) *F1Update {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *F1Update) SetToken(v string) *F1Update {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *F1Update) SetNillableToken(v *string) *F1Update {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *F1Update) SetURL(v string) *F1Update {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *F1Update) SetNillableURL(v *string) *F1Update {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the F1Mutation object of the builder.
func (_u *F1Update) Mutation() *F1Mutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *F1Update) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *F1Update) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *F1Update) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *F1Update) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *F1Update) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(f1.Table, f1.Columns, sqlgraph.NewFieldSpec(f1.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(f1.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(f1.FieldURL, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{f1.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// F1UpdateOne is the builder for updating a single F1 entity.
type F1UpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *F1Mutation
}

// SetToken sets the "token" field.
func (_u *F1UpdateOne) SetToken(v string) *F1UpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *F1UpdateOne) SetNillableToken(v *string) *F1UpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *F1UpdateOne) SetURL(v string) *F1UpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *F1UpdateOne) SetNillableURL(v *string) *F1UpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the F1Mutation object of the builder.
func (_u *F1UpdateOne) Mutation() *F1Mutation {
	return _u.mutation
}

// Where appends a list predicates to the F1Update builder.
func (_u *F1UpdateOne) Where(ps ...predicate.F1) *F1UpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *F1UpdateOne) Select(field string, fields ...string) *F1UpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated F1 entity.
func (_u *F1UpdateOne) Save(ctx context.Context) (*F1, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *F1UpdateOne) SaveX(ctx context.Context) *F1 {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *F1UpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *F1UpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *F1UpdateOne) sqlSave(ctx context.Context) (_node *F1, err error) {
	_spec := sqlgraph.NewUpdateSpec(f1.Table, f1.Columns, sqlgraph.NewFieldSpec(f1.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "F1.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, f1.FieldID)
		for _, f := range fields {
			if !f1.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != f1.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(f1.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(f1.FieldURL, field.TypeString, value)
	}
	_node = &F1{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{f1.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
