// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ledit/ent/firmwaresettings"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FirmwareSettingsDelete is the builder for deleting a FirmwareSettings entity.
type FirmwareSettingsDelete struct {
	config
	hooks    []Hook
	mutation *FirmwareSettingsMutation
}

// Where appends a list predicates to the FirmwareSettingsDelete builder.
func (_d *FirmwareSettingsDelete) Where(ps ...predicate.FirmwareSettings) *FirmwareSettingsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FirmwareSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FirmwareSettingsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FirmwareSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(firmwaresettings.Table, sqlgraph.NewFieldSpec(firmwaresettings.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FirmwareSettingsDeleteOne is the builder for deleting a single FirmwareSettings entity.
type FirmwareSettingsDeleteOne struct {
	_d *FirmwareSettingsDelete
}

// Where appends a list predicates to the FirmwareSettingsDelete builder.
func (_d *FirmwareSettingsDeleteOne) Where(ps ...predicate.FirmwareSettings) *FirmwareSettingsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FirmwareSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{firmwaresettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FirmwareSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
