// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/frigate"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Frigate is the model entity for the Frigate schema.
type Frigate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Frigate API token
	Token string `json:"token,omitempty"`
	// Frigate stats API URL
	URL                       string `json:"url,omitempty"`
	general_settings_frigates *int
	selectValues              sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Frigate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case frigate.FieldID:
			values[i] = new(sql.NullInt64)
		case frigate.FieldToken, frigate.FieldURL:
			values[i] = new(sql.NullString)
		case frigate.ForeignKeys[0]: // general_settings_frigates
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Frigate fields.
func (_m *Frigate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case frigate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case frigate.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case frigate.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case frigate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field general_settings_frigates", value)
			} else if value.Valid {
				_m.general_settings_frigates = new(int)
				*_m.general_settings_frigates = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Frigate.
// This includes values selected through modifiers, order, etc.
func (_m *Frigate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Frigate.
// Note that you need to call Frigate.Unwrap() before calling this method if this Frigate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Frigate) Update() *FrigateUpdateOne {
	return NewFrigateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Frigate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Frigate) Unwrap() *Frigate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Frigate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Frigate) String() string {
	var builder strings.Builder
	builder.WriteString("Frigate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteByte(')')
	return builder.String()
}

// Frigates is a parsable slice of Frigate.
type Frigates []*Frigate
