// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ledit/ent/genericapi"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GenericAPIDelete is the builder for deleting a GenericAPI entity.
type GenericAPIDelete struct {
	config
	hooks    []Hook
	mutation *GenericAPIMutation
}

// Where appends a list predicates to the GenericAPIDelete builder.
func (_d *GenericAPIDelete) Where(ps ...predicate.GenericAPI) *GenericAPIDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GenericAPIDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GenericAPIDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GenericAPIDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(genericapi.Table, sqlgraph.NewFieldSpec(genericapi.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GenericAPIDeleteOne is the builder for deleting a single GenericAPI entity.
type GenericAPIDeleteOne struct {
	_d *GenericAPIDelete
}

// Where appends a list predicates to the GenericAPIDelete builder.
func (_d *GenericAPIDeleteOne) Where(ps ...predicate.GenericAPI) *GenericAPIDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GenericAPIDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{genericapi.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GenericAPIDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
