// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/guestphoto"
	"ledit/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuestPhotoUpdate is the builder for updating GuestPhoto entities.
type GuestPhotoUpdate struct {
	config
	hooks    []Hook
	mutation *GuestPhotoMutation
}

// Where appends a list predicates to the GuestPhotoUpdate builder.
func (_u *GuestPhotoUpdate) Where(ps ...predicate.GuestPhoto) *GuestPhotoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPath sets the "path" field.
func (_u *GuestPhotoUpdate) SetPath(v string) *GuestPhotoUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillablePath(v *string) *GuestPhotoUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetGuestTokenID sets the "guest_token_id" field.
func (_u *GuestPhotoUpdate) SetGuestTokenID(v int) *GuestPhotoUpdate {
	_u.mutation.ResetGuestTokenID()
	_u.mutation.SetGuestTokenID(v)
	return _u
}

// SetNillableGuestTokenID sets the "guest_token_id" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillableGuestTokenID(v *int) *GuestPhotoUpdate {
	if v != nil {
		_u.SetGuestTokenID(*v)
	}
	return _u
}

// AddGuestTokenID adds value to the "guest_token_id" field.
func (_u *GuestPhotoUpdate) AddGuestTokenID(v int) *GuestPhotoUpdate {
	_u.mutation.AddGuestTokenID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GuestPhotoUpdate) SetStatus(v guestphoto.Status) *GuestPhotoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillableStatus(v *guestphoto.Status) *GuestPhotoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *GuestPhotoUpdate) SetBytes(v int) *GuestPhotoUpdate {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillableBytes(v *int) *GuestPhotoUpdate {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *GuestPhotoUpdate) AddBytes(v int) *GuestPhotoUpdate {
	_u.mutation.AddBytes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GuestPhotoUpdate) SetCreatedAt(v time.Time) *GuestPhotoUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillableCreatedAt(v *time.Time) *GuestPhotoUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuestPhotoUpdate) SetUpdatedAt(v time.Time) *GuestPhotoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GuestPhotoUpdate) SetExpiresAt(v time.Time) *GuestPhotoUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GuestPhotoUpdate) SetNillableExpiresAt(v *time.Time) *GuestPhotoUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GuestPhotoUpdate) ClearExpiresAt() *GuestPhotoUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the GuestPhotoMutation object of the builder.
func (_u *GuestPhotoUpdate) Mutation() *GuestPhotoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GuestPhotoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuestPhotoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GuestPhotoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuestPhotoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuestPhotoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guestphoto.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuestPhotoUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := guestphoto.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GuestPhoto.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GuestPhotoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guestphoto.Table, guestphoto.Columns, sqlgraph.NewFieldSpec(guestphoto.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(guestphoto.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.GuestTokenID(); ok {
		_spec.SetField(guestphoto.FieldGuestTokenID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGuestTokenID(); ok {
		_spec.AddField(guestphoto.FieldGuestTokenID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(guestphoto.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(guestphoto.FieldBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(guestphoto.FieldBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(guestphoto.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guestphoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(guestphoto.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(guestphoto.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guestphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GuestPhotoUpdateOne is the builder for updating a single GuestPhoto entity.
type GuestPhotoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GuestPhotoMutation
}

// SetPath sets the "path" field.
func (_u *GuestPhotoUpdateOne) SetPath(v string) *GuestPhotoUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillablePath(v *string) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetGuestTokenID sets the "guest_token_id" field.
func (_u *GuestPhotoUpdateOne) SetGuestTokenID(v int) *GuestPhotoUpdateOne {
	_u.mutation.ResetGuestTokenID()
	_u.mutation.SetGuestTokenID(v)
	return _u
}

// SetNillableGuestTokenID sets the "guest_token_id" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillableGuestTokenID(v *int) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetGuestTokenID(*v)
	}
	return _u
}

// AddGuestTokenID adds value to the "guest_token_id" field.
func (_u *GuestPhotoUpdateOne) AddGuestTokenID(v int) *GuestPhotoUpdateOne {
	_u.mutation.AddGuestTokenID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GuestPhotoUpdateOne) SetStatus(v guestphoto.Status) *GuestPhotoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillableStatus(v *guestphoto.Status) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *GuestPhotoUpdateOne) SetBytes(v int) *GuestPhotoUpdateOne {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillableBytes(v *int) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *GuestPhotoUpdateOne) AddBytes(v int) *GuestPhotoUpdateOne {
	_u.mutation.AddBytes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GuestPhotoUpdateOne) SetCreatedAt(v time.Time) *GuestPhotoUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillableCreatedAt(v *time.Time) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuestPhotoUpdateOne) SetUpdatedAt(v time.Time) *GuestPhotoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GuestPhotoUpdateOne) SetExpiresAt(v time.Time) *GuestPhotoUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GuestPhotoUpdateOne) SetNillableExpiresAt(v *time.Time) *GuestPhotoUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GuestPhotoUpdateOne) ClearExpiresAt() *GuestPhotoUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the GuestPhotoMutation object of the builder.
func (_u *GuestPhotoUpdateOne) Mutation() *GuestPhotoMutation {
	return _u.mutation
}

// Where appends a list predicates to the GuestPhotoUpdate builder.
func (_u *GuestPhotoUpdateOne) Where(ps ...predicate.GuestPhoto) *GuestPhotoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GuestPhotoUpdateOne) Select(field string, fields ...string) *GuestPhotoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GuestPhoto entity.
func (_u *GuestPhotoUpdateOne) Save(ctx context.Context) (*GuestPhoto, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuestPhotoUpdateOne) SaveX(ctx context.Context) *GuestPhoto {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GuestPhotoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuestPhotoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuestPhotoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guestphoto.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuestPhotoUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := guestphoto.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GuestPhoto.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GuestPhotoUpdateOne) sqlSave(ctx context.Context) (_node *GuestPhoto, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guestphoto.Table, guestphoto.Columns, sqlgraph.NewFieldSpec(guestphoto.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GuestPhoto.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guestphoto.FieldID)
		for _, f := range fields {
			if !guestphoto.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != guestphoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(guestphoto.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.GuestTokenID(); ok {
		_spec.SetField(guestphoto.FieldGuestTokenID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGuestTokenID(); ok {
		_spec.AddField(guestphoto.FieldGuestTokenID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(guestphoto.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(guestphoto.FieldBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(guestphoto.FieldBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(guestphoto.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guestphoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(guestphoto.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(guestphoto.FieldExpiresAt, field.TypeTime)
	}
	_node = &GuestPhoto{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guestphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
