// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/jellyfin"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Jellyfin is the model entity for the Jellyfin schema.
type Jellyfin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Jellyfin API token (X-Emby-Token)
	Token string `json:"token,omitempty"`
	// Jellyfin server base URL
	URL                        string `json:"url,omitempty"`
	general_settings_jellyfins *int
	selectValues               sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Jellyfin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jellyfin.FieldID:
			values[i] = new(sql.NullInt64)
		case jellyfin.FieldToken, jellyfin.FieldURL:
			values[i] = new(sql.NullString)
		case jellyfin.ForeignKeys[0]: // general_settings_jellyfins
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Jellyfin fields.
func (_m *Jellyfin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jellyfin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case jellyfin.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case jellyfin.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case jellyfin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field general_settings_jellyfins", value)
			} else if value.Valid {
				_m.general_settings_jellyfins = new(int)
				*_m.general_settings_jellyfins = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Jellyfin.
// This includes values selected through modifiers, order, etc.
func (_m *Jellyfin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Jellyfin.
// Note that you need to call Jellyfin.Unwrap() before calling this method if this Jellyfin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Jellyfin) Update() *JellyfinUpdateOne {
	return NewJellyfinClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Jellyfin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Jellyfin) Unwrap() *Jellyfin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Jellyfin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Jellyfin) String() string {
	var builder strings.Builder
	builder.WriteString("Jellyfin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteByte(')')
	return builder.String()
}

// Jellyfins is a parsable slice of Jellyfin.
type Jellyfins []*Jellyfin
