// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/logsettings"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogSettingsUpdate is the builder for updating LogSettings entities.
type LogSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *LogSettingsMutation
}

// Where appends a list predicates to the LogSettingsUpdate builder.
func (_u *LogSettingsUpdate) Where(ps ...predicate.LogSettings) *LogSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVerbosity sets the "verbosity" field.
func (_u *LogSettingsUpdate) SetVerbosity(v string) *LogSettingsUpdate {
	_u.mutation.SetVerbosity(v)
	return _u
}

// SetNillableVerbosity sets the "verbosity" field if the given value is not nil.
func (_u *LogSettingsUpdate) SetNillableVerbosity(v *string) *LogSettingsUpdate {
	if v != nil {
		_u.SetVerbosity(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *LogSettingsUpdate) SetRetentionDays(v int) *LogSettingsUpdate {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *LogSettingsUpdate) SetNillableRetentionDays(v *int) *LogSettingsUpdate {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *LogSettingsUpdate) AddRetentionDays(v int) *LogSettingsUpdate {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetOtelEndpoint sets the "otel_endpoint" field.
func (_u *LogSettingsUpdate) SetOtelEndpoint(v string) *LogSettingsUpdate {
	_u.mutation.SetOtelEndpoint(v)
	return _u
}

// SetNillableOtelEndpoint sets the "otel_endpoint" field if the given value is not nil.
func (_u *LogSettingsUpdate) SetNillableOtelEndpoint(v *string) *LogSettingsUpdate {
	if v != nil {
		_u.SetOtelEndpoint(*v)
	}
	return _u
}

// ClearOtelEndpoint clears the value of the "otel_endpoint" field.
func (_u *LogSettingsUpdate) ClearOtelEndpoint() *LogSettingsUpdate {
	_u.mutation.ClearOtelEndpoint()
	return _u
}

// SetOtelProtocol sets the "otel_protocol" field.
func (_u *LogSettingsUpdate) SetOtelProtocol(v string) *LogSettingsUpdate {
	_u.mutation.SetOtelProtocol(v)
	return _u
}

// SetNillableOtelProtocol sets the "otel_protocol" field if the given value is not nil.
func (_u *LogSettingsUpdate) SetNillableOtelProtocol(v *string) *LogSettingsUpdate {
	if v != nil {
		_u.SetOtelProtocol(*v)
	}
	return _u
}

// ClearOtelProtocol clears the value of the "otel_protocol" field.
func (_u *LogSettingsUpdate) ClearOtelProtocol() *LogSettingsUpdate {
	_u.mutation.ClearOtelProtocol()
	return _u
}

// SetOtelEnabled sets the "otel_enabled" field.
func (_u *LogSettingsUpdate) SetOtelEnabled(v bool) *LogSettingsUpdate {
	_u.mutation.SetOtelEnabled(v)
	return _u
}

// SetNillableOtelEnabled sets the "otel_enabled" field if the given value is not nil.
func (_u *LogSettingsUpdate) SetNillableOtelEnabled(v *bool) *LogSettingsUpdate {
	if v != nil {
		_u.SetOtelEnabled(*v)
	}
	return _u
}

// Mutation returns the LogSettingsMutation object of the builder.
func (_u *LogSettingsUpdate) Mutation() *LogSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LogSettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LogSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LogSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(logsettings.Table, logsettings.Columns, sqlgraph.NewFieldSpec(logsettings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Verbosity(); ok {
		_spec.SetField(logsettings.FieldVerbosity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(logsettings.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(logsettings.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OtelEndpoint(); ok {
		_spec.SetField(logsettings.FieldOtelEndpoint, field.TypeString, value)
	}
	if _u.mutation.OtelEndpointCleared() {
		_spec.ClearField(logsettings.FieldOtelEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.OtelProtocol(); ok {
		_spec.SetField(logsettings.FieldOtelProtocol, field.TypeString, value)
	}
	if _u.mutation.OtelProtocolCleared() {
		_spec.ClearField(logsettings.FieldOtelProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.OtelEnabled(); ok {
		_spec.SetField(logsettings.FieldOtelEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LogSettingsUpdateOne is the builder for updating a single LogSettings entity.
type LogSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LogSettingsMutation
}

// SetVerbosity sets the "verbosity" field.
func (_u *LogSettingsUpdateOne) SetVerbosity(v string) *LogSettingsUpdateOne {
	_u.mutation.SetVerbosity(v)
	return _u
}

// SetNillableVerbosity sets the "verbosity" field if the given value is not nil.
func (_u *LogSettingsUpdateOne) SetNillableVerbosity(v *string) *LogSettingsUpdateOne {
	if v != nil {
		_u.SetVerbosity(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *LogSettingsUpdateOne) SetRetentionDays(v int) *LogSettingsUpdateOne {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *LogSettingsUpdateOne) SetNillableRetentionDays(v *int) *LogSettingsUpdateOne {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *LogSettingsUpdateOne) AddRetentionDays(v int) *LogSettingsUpdateOne {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetOtelEndpoint sets the "otel_endpoint" field.
func (_u *LogSettingsUpdateOne) SetOtelEndpoint(v string) *LogSettingsUpdateOne {
	_u.mutation.SetOtelEndpoint(v)
	return _u
}

// SetNillableOtelEndpoint sets the "otel_endpoint" field if the given value is not nil.
func (_u *LogSettingsUpdateOne) SetNillableOtelEndpoint(v *string) *LogSettingsUpdateOne {
	if v != nil {
		_u.SetOtelEndpoint(*v)
	}
	return _u
}

// ClearOtelEndpoint clears the value of the "otel_endpoint" field.
func (_u *LogSettingsUpdateOne) ClearOtelEndpoint() *LogSettingsUpdateOne {
	_u.mutation.ClearOtelEndpoint()
	return _u
}

// SetOtelProtocol sets the "otel_protocol" field.
func (_u *LogSettingsUpdateOne) SetOtelProtocol(v string) *LogSettingsUpdateOne {
	_u.mutation.SetOtelProtocol(v)
	return _u
}

// SetNillableOtelProtocol sets the "otel_protocol" field if the given value is not nil.
func (_u *LogSettingsUpdateOne) SetNillableOtelProtocol(v *string) *LogSettingsUpdateOne {
	if v != nil {
		_u.SetOtelProtocol(*v)
	}
	return _u
}

// ClearOtelProtocol clears the value of the "otel_protocol" field.
func (_u *LogSettingsUpdateOne) ClearOtelProtocol() *LogSettingsUpdateOne {
	_u.mutation.ClearOtelProtocol()
	return _u
}

// SetOtelEnabled sets the "otel_enabled" field.
func (_u *LogSettingsUpdateOne) SetOtelEnabled(v bool) *LogSettingsUpdateOne {
	_u.mutation.SetOtelEnabled(v)
	return _u
}

// SetNillableOtelEnabled sets the "otel_enabled" field if the given value is not nil.
func (_u *LogSettingsUpdateOne) SetNillableOtelEnabled(v *bool) *LogSettingsUpdateOne {
	if v != nil {
		_u.SetOtelEnabled(*v)
	}
	return _u
}

// Mutation returns the LogSettingsMutation object of the builder.
func (_u *LogSettingsUpdateOne) Mutation() *LogSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the LogSettingsUpdate builder.
func (_u *LogSettingsUpdateOne) Where(ps ...predicate.LogSettings) *LogSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LogSettingsUpdateOne) Select(field string, fields ...string) *LogSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LogSettings entity.
func (_u *LogSettingsUpdateOne) Save(ctx context.Context) (*LogSettings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogSettingsUpdateOne) SaveX(ctx context.Context) *LogSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LogSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LogSettingsUpdateOne) sqlSave(ctx context.Context) (_node *LogSettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(logsettings.Table, logsettings.Columns, sqlgraph.NewFieldSpec(logsettings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LogSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logsettings.FieldID)
		for _, f := range fields {
			if !logsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Verbosity(); ok {
		_spec.SetField(logsettings.FieldVerbosity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(logsettings.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(logsettings.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OtelEndpoint(); ok {
		_spec.SetField(logsettings.FieldOtelEndpoint, field.TypeString, value)
	}
	if _u.mutation.OtelEndpointCleared() {
		_spec.ClearField(logsettings.FieldOtelEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.OtelProtocol(); ok {
		_spec.SetField(logsettings.FieldOtelProtocol, field.TypeString, value)
	}
	if _u.mutation.OtelProtocolCleared() {
		_spec.ClearField(logsettings.FieldOtelProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.OtelEnabled(); ok {
		_spec.SetField(logsettings.FieldOtelEnabled, field.TypeBool, value)
	}
	_node = &LogSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
