// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/overseerr"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OverseerrUpdate is the builder for updating Overseerr entities.
type OverseerrUpdate struct {
	config
	hooks    []Hook
	mutation *OverseerrMutation
}

// Where appends a list predicates to the OverseerrUpdate builder.
func (_u *OverseerrUpdate) Where(ps ...predicate.Overseerr) *OverseerrUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *OverseerrUpdate) SetToken(v string) *OverseerrUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *OverseerrUpdate) SetNillableToken(v *string) *OverseerrUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *OverseerrUpdate) SetURL(v string) *OverseerrUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *OverseerrUpdate) SetNillableURL(v *string) *OverseerrUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the OverseerrMutation object of the builder.
func (_u *OverseerrUpdate) Mutation() *OverseerrMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OverseerrUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OverseerrUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OverseerrUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OverseerrUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OverseerrUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(overseerr.Table, overseerr.Columns, sqlgraph.NewFieldSpec(overseerr.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(overseerr.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(overseerr.FieldURL, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{overseerr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OverseerrUpdateOne is the builder for updating a single Overseerr entity.
type OverseerrUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OverseerrMutation
}

// SetToken sets the "token" field.
func (_u *OverseerrUpdateOne) SetToken(v string) *OverseerrUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *OverseerrUpdateOne) SetNillableToken(v *string) *OverseerrUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *OverseerrUpdateOne) SetURL(v string) *OverseerrUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *OverseerrUpdateOne) SetNillableURL(v *string) *OverseerrUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the OverseerrMutation object of the builder.
func (_u *OverseerrUpdateOne) Mutation() *OverseerrMutation {
	return _u.mutation
}

// Where appends a list predicates to the OverseerrUpdate builder.
func (_u *OverseerrUpdateOne) Where(ps ...predicate.Overseerr) *OverseerrUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OverseerrUpdateOne) Select(field string, fields ...string) *OverseerrUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Overseerr entity.
func (_u *OverseerrUpdateOne) Save(ctx context.Context) (*Overseerr, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OverseerrUpdateOne) SaveX(ctx context.Context) *Overseerr {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OverseerrUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OverseerrUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OverseerrUpdateOne) sqlSave(ctx context.Context) (_node *Overseerr, err error) {
	_spec := sqlgraph.NewUpdateSpec(overseerr.Table, overseerr.Columns, sqlgraph.NewFieldSpec(overseerr.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Overseerr.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, overseerr.FieldID)
		for _, f := range fields {
			if !overseerr.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != overseerr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(overseerr.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(overseerr.FieldURL, field.TypeString, value)
	}
	_node = &Overseerr{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{overseerr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
