// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/parcel"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ParcelCreate is the builder for creating a Parcel entity.
type ParcelCreate struct {
	config
	mutation *ParcelMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (_c *ParcelCreate) SetToken(v string) *ParcelCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *ParcelCreate) SetNillableToken(v *string) *ParcelCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *ParcelCreate) SetURL(v string) *ParcelCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *ParcelCreate) SetNillableURL(v *string) *ParcelCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// Mutation returns the ParcelMutation object of the builder.
func (_c *ParcelCreate) Mutation() *ParcelMutation {
	return _c.mutation
}

// Save creates the Parcel in the database.
func (_c *ParcelCreate) Save(ctx context.Context) (*Parcel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParcelCreate) SaveX(ctx context.Context) *Parcel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParcelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParcelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ParcelCreate) defaults() {
	if _, ok := _c.mutation.Token(); !ok {
		v := parcel.DefaultToken
		_c.mutation.SetToken(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := parcel.DefaultURL
		_c.mutation.SetURL(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParcelCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Parcel.token"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Parcel.url"`)}
	}
	return nil
}

func (_c *ParcelCreate) sqlSave(ctx context.Context) (*Parcel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ParcelCreate) createSpec() (*Parcel, *sqlgraph.CreateSpec) {
	var (
		_node = &Parcel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(parcel.Table, sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(parcel.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(parcel.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// ParcelCreateBulk is the builder for creating many Parcel entities in bulk.
type ParcelCreateBulk struct {
	config
	err      error
	builders []*ParcelCreate
}

// Save creates the Parcel entities in the database.
func (_c *ParcelCreateBulk) Save(ctx context.Context) ([]*Parcel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Parcel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParcelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParcelCreateBulk) SaveX(ctx context.Context) []*Parcel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParcelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParcelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
