// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/pixelart"
	"ledit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PixelArtUpdate is the builder for updating PixelArt entities.
type PixelArtUpdate struct {
	config
	hooks    []Hook
	mutation *PixelArtMutation
}

// Where appends a list predicates to the PixelArtUpdate builder.
func (_u *PixelArtUpdate) Where(ps ...predicate.PixelArt) *PixelArtUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PixelArtUpdate) SetName(v string) *PixelArtUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableName(v *string) *PixelArtUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGridWidth sets the "grid_width" field.
func (_u *PixelArtUpdate) SetGridWidth(v int) *PixelArtUpdate {
	_u.mutation.ResetGridWidth()
	_u.mutation.SetGridWidth(v)
	return _u
}

// SetNillableGridWidth sets the "grid_width" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableGridWidth(v *int) *PixelArtUpdate {
	if v != nil {
		_u.SetGridWidth(*v)
	}
	return _u
}

// AddGridWidth adds value to the "grid_width" field.
func (_u *PixelArtUpdate) AddGridWidth(v int) *PixelArtUpdate {
	_u.mutation.AddGridWidth(v)
	return _u
}

// SetGridHeight sets the "grid_height" field.
func (_u *PixelArtUpdate) SetGridHeight(v int) *PixelArtUpdate {
	_u.mutation.ResetGridHeight()
	_u.mutation.SetGridHeight(v)
	return _u
}

// SetNillableGridHeight sets the "grid_height" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableGridHeight(v *int) *PixelArtUpdate {
	if v != nil {
		_u.SetGridHeight(*v)
	}
	return _u
}

// AddGridHeight adds value to the "grid_height" field.
func (_u *PixelArtUpdate) AddGridHeight(v int) *PixelArtUpdate {
	_u.mutation.AddGridHeight(v)
	return _u
}

// SetFrames sets the "frames" field.
func (_u *PixelArtUpdate) SetFrames(v string) *PixelArtUpdate {
	_u.mutation.SetFrames(v)
	return _u
}

// SetNillableFrames sets the "frames" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableFrames(v *string) *PixelArtUpdate {
	if v != nil {
		_u.SetFrames(*v)
	}
	return _u
}

// SetBindings sets the "bindings" field.
func (_u *PixelArtUpdate) SetBindings(v string) *PixelArtUpdate {
	_u.mutation.SetBindings(v)
	return _u
}

// SetNillableBindings sets the "bindings" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableBindings(v *string) *PixelArtUpdate {
	if v != nil {
		_u.SetBindings(*v)
	}
	return _u
}

// SetAPIURL sets the "api_url" field.
func (_u *PixelArtUpdate) SetAPIURL(v string) *PixelArtUpdate {
	_u.mutation.SetAPIURL(v)
	return _u
}

// SetNillableAPIURL sets the "api_url" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableAPIURL(v *string) *PixelArtUpdate {
	if v != nil {
		_u.SetAPIURL(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *PixelArtUpdate) SetAPIToken(v string) *PixelArtUpdate {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableAPIToken(v *string) *PixelArtUpdate {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PixelArtUpdate) SetEnabled(v bool) *PixelArtUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableEnabled(v *bool) *PixelArtUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIsDraft sets the "is_draft" field.
func (_u *PixelArtUpdate) SetIsDraft(v bool) *PixelArtUpdate {
	_u.mutation.SetIsDraft(v)
	return _u
}

// SetNillableIsDraft sets the "is_draft" field if the given value is not nil.
func (_u *PixelArtUpdate) SetNillableIsDraft(v *bool) *PixelArtUpdate {
	if v != nil {
		_u.SetIsDraft(*v)
	}
	return _u
}

// Mutation returns the PixelArtMutation object of the builder.
func (_u *PixelArtUpdate) Mutation() *PixelArtMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PixelArtUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PixelArtUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PixelArtUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PixelArtUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PixelArtUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pixelart.Table, pixelart.Columns, sqlgraph.NewFieldSpec(pixelart.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pixelart.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GridWidth(); ok {
		_spec.SetField(pixelart.FieldGridWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridWidth(); ok {
		_spec.AddField(pixelart.FieldGridWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridHeight(); ok {
		_spec.SetField(pixelart.FieldGridHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridHeight(); ok {
		_spec.AddField(pixelart.FieldGridHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Frames(); ok {
		_spec.SetField(pixelart.FieldFrames, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bindings(); ok {
		_spec.SetField(pixelart.FieldBindings, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIURL(); ok {
		_spec.SetField(pixelart.FieldAPIURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(pixelart.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pixelart.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDraft(); ok {
		_spec.SetField(pixelart.FieldIsDraft, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pixelart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PixelArtUpdateOne is the builder for updating a single PixelArt entity.
type PixelArtUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PixelArtMutation
}

// SetName sets the "name" field.
func (_u *PixelArtUpdateOne) SetName(v string) *PixelArtUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableName(v *string) *PixelArtUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGridWidth sets the "grid_width" field.
func (_u *PixelArtUpdateOne) SetGridWidth(v int) *PixelArtUpdateOne {
	_u.mutation.ResetGridWidth()
	_u.mutation.SetGridWidth(v)
	return _u
}

// SetNillableGridWidth sets the "grid_width" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableGridWidth(v *int) *PixelArtUpdateOne {
	if v != nil {
		_u.SetGridWidth(*v)
	}
	return _u
}

// AddGridWidth adds value to the "grid_width" field.
func (_u *PixelArtUpdateOne) AddGridWidth(v int) *PixelArtUpdateOne {
	_u.mutation.AddGridWidth(v)
	return _u
}

// SetGridHeight sets the "grid_height" field.
func (_u *PixelArtUpdateOne) SetGridHeight(v int) *PixelArtUpdateOne {
	_u.mutation.ResetGridHeight()
	_u.mutation.SetGridHeight(v)
	return _u
}

// SetNillableGridHeight sets the "grid_height" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableGridHeight(v *int) *PixelArtUpdateOne {
	if v != nil {
		_u.SetGridHeight(*v)
	}
	return _u
}

// AddGridHeight adds value to the "grid_height" field.
func (_u *PixelArtUpdateOne) AddGridHeight(v int) *PixelArtUpdateOne {
	_u.mutation.AddGridHeight(v)
	return _u
}

// SetFrames sets the "frames" field.
func (_u *PixelArtUpdateOne) SetFrames(v string) *PixelArtUpdateOne {
	_u.mutation.SetFrames(v)
	return _u
}

// SetNillableFrames sets the "frames" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableFrames(v *string) *PixelArtUpdateOne {
	if v != nil {
		_u.SetFrames(*v)
	}
	return _u
}

// SetBindings sets the "bindings" field.
func (_u *PixelArtUpdateOne) SetBindings(v string) *PixelArtUpdateOne {
	_u.mutation.SetBindings(v)
	return _u
}

// SetNillableBindings sets the "bindings" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableBindings(v *string) *PixelArtUpdateOne {
	if v != nil {
		_u.SetBindings(*v)
	}
	return _u
}

// SetAPIURL sets the "api_url" field.
func (_u *PixelArtUpdateOne) SetAPIURL(v string) *PixelArtUpdateOne {
	_u.mutation.SetAPIURL(v)
	return _u
}

// SetNillableAPIURL sets the "api_url" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableAPIURL(v *string) *PixelArtUpdateOne {
	if v != nil {
		_u.SetAPIURL(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *PixelArtUpdateOne) SetAPIToken(v string) *PixelArtUpdateOne {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableAPIToken(v *string) *PixelArtUpdateOne {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PixelArtUpdateOne) SetEnabled(v bool) *PixelArtUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableEnabled(v *bool) *PixelArtUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIsDraft sets the "is_draft" field.
func (_u *PixelArtUpdateOne) SetIsDraft(v bool) *PixelArtUpdateOne {
	_u.mutation.SetIsDraft(v)
	return _u
}

// SetNillableIsDraft sets the "is_draft" field if the given value is not nil.
func (_u *PixelArtUpdateOne) SetNillableIsDraft(v *bool) *PixelArtUpdateOne {
	if v != nil {
		_u.SetIsDraft(*v)
	}
	return _u
}

// Mutation returns the PixelArtMutation object of the builder.
func (_u *PixelArtUpdateOne) Mutation() *PixelArtMutation {
	return _u.mutation
}

// Where appends a list predicates to the PixelArtUpdate builder.
func (_u *PixelArtUpdateOne) Where(ps ...predicate.PixelArt) *PixelArtUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PixelArtUpdateOne) Select(field string, fields ...string) *PixelArtUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PixelArt entity.
func (_u *PixelArtUpdateOne) Save(ctx context.Context) (*PixelArt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PixelArtUpdateOne) SaveX(ctx context.Context) *PixelArt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PixelArtUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PixelArtUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PixelArtUpdateOne) sqlSave(ctx context.Context) (_node *PixelArt, err error) {
	_spec := sqlgraph.NewUpdateSpec(pixelart.Table, pixelart.Columns, sqlgraph.NewFieldSpec(pixelart.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PixelArt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pixelart.FieldID)
		for _, f := range fields {
			if !pixelart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pixelart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pixelart.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GridWidth(); ok {
		_spec.SetField(pixelart.FieldGridWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridWidth(); ok {
		_spec.AddField(pixelart.FieldGridWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridHeight(); ok {
		_spec.SetField(pixelart.FieldGridHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridHeight(); ok {
		_spec.AddField(pixelart.FieldGridHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Frames(); ok {
		_spec.SetField(pixelart.FieldFrames, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bindings(); ok {
		_spec.SetField(pixelart.FieldBindings, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIURL(); ok {
		_spec.SetField(pixelart.FieldAPIURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(pixelart.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pixelart.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDraft(); ok {
		_spec.SetField(pixelart.FieldIsDraft, field.TypeBool, value)
	}
	_node = &PixelArt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pixelart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
