// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/predicate"
	"ledit/ent/proxmox"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProxmoxUpdate is the builder for updating Proxmox entities.
type ProxmoxUpdate struct {
	config
	hooks    []Hook
	mutation *ProxmoxMutation
}

// Where appends a list predicates to the ProxmoxUpdate builder.
func (_u *ProxmoxUpdate) Where(ps ...predicate.Proxmox) *ProxmoxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *ProxmoxUpdate) SetToken(v string) *ProxmoxUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ProxmoxUpdate) SetNillableToken(v *string) *ProxmoxUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ProxmoxUpdate) SetURL(v string) *ProxmoxUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ProxmoxUpdate) SetNillableURL(v *string) *ProxmoxUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the ProxmoxMutation object of the builder.
func (_u *ProxmoxUpdate) Mutation() *ProxmoxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxmoxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxmoxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxmoxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxmoxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProxmoxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(proxmox.Table, proxmox.Columns, sqlgraph.NewFieldSpec(proxmox.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(proxmox.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(proxmox.FieldURL, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxmox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxmoxUpdateOne is the builder for updating a single Proxmox entity.
type ProxmoxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxmoxMutation
}

// SetToken sets the "token" field.
func (_u *ProxmoxUpdateOne) SetToken(v string) *ProxmoxUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ProxmoxUpdateOne) SetNillableToken(v *string) *ProxmoxUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ProxmoxUpdateOne) SetURL(v string) *ProxmoxUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ProxmoxUpdateOne) SetNillableURL(v *string) *ProxmoxUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the ProxmoxMutation object of the builder.
func (_u *ProxmoxUpdateOne) Mutation() *ProxmoxMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxmoxUpdate builder.
func (_u *ProxmoxUpdateOne) Where(ps ...predicate.Proxmox) *ProxmoxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxmoxUpdateOne) Select(field string, fields ...string) *ProxmoxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Proxmox entity.
func (_u *ProxmoxUpdateOne) Save(ctx context.Context) (*Proxmox, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxmoxUpdateOne) SaveX(ctx context.Context) *Proxmox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxmoxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxmoxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProxmoxUpdateOne) sqlSave(ctx context.Context) (_node *Proxmox, err error) {
	_spec := sqlgraph.NewUpdateSpec(proxmox.Table, proxmox.Columns, sqlgraph.NewFieldSpec(proxmox.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Proxmox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxmox.FieldID)
		for _, f := range fields {
			if !proxmox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxmox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(proxmox.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(proxmox.FieldURL, field.TypeString, value)
	}
	_node = &Proxmox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxmox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
