// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/qrcode"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QrcodeCreate is the builder for creating a Qrcode entity.
type QrcodeCreate struct {
	config
	mutation *QrcodeMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *QrcodeCreate) SetContent(v string) *QrcodeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *QrcodeCreate) SetMode(v qrcode.Mode) *QrcodeCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableMode(v *qrcode.Mode) *QrcodeCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetWifiSsid sets the "wifi_ssid" field.
func (_c *QrcodeCreate) SetWifiSsid(v string) *QrcodeCreate {
	_c.mutation.SetWifiSsid(v)
	return _c
}

// SetNillableWifiSsid sets the "wifi_ssid" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableWifiSsid(v *string) *QrcodeCreate {
	if v != nil {
		_c.SetWifiSsid(*v)
	}
	return _c
}

// SetWifiPassword sets the "wifi_password" field.
func (_c *QrcodeCreate) SetWifiPassword(v string) *QrcodeCreate {
	_c.mutation.SetWifiPassword(v)
	return _c
}

// SetNillableWifiPassword sets the "wifi_password" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableWifiPassword(v *string) *QrcodeCreate {
	if v != nil {
		_c.SetWifiPassword(*v)
	}
	return _c
}

// SetWifiAuth sets the "wifi_auth" field.
func (_c *QrcodeCreate) SetWifiAuth(v qrcode.WifiAuth) *QrcodeCreate {
	_c.mutation.SetWifiAuth(v)
	return _c
}

// SetNillableWifiAuth sets the "wifi_auth" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableWifiAuth(v *qrcode.WifiAuth) *QrcodeCreate {
	if v != nil {
		_c.SetWifiAuth(*v)
	}
	return _c
}

// SetCaption sets the "caption" field.
func (_c *QrcodeCreate) SetCaption(v string) *QrcodeCreate {
	_c.mutation.SetCaption(v)
	return _c
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableCaption(v *string) *QrcodeCreate {
	if v != nil {
		_c.SetCaption(*v)
	}
	return _c
}

// SetErrorCorrection sets the "error_correction" field.
func (_c *QrcodeCreate) SetErrorCorrection(v qrcode.ErrorCorrection) *QrcodeCreate {
	_c.mutation.SetErrorCorrection(v)
	return _c
}

// SetNillableErrorCorrection sets the "error_correction" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableErrorCorrection(v *qrcode.ErrorCorrection) *QrcodeCreate {
	if v != nil {
		_c.SetErrorCorrection(*v)
	}
	return _c
}

// SetQuietZone sets the "quiet_zone" field.
func (_c *QrcodeCreate) SetQuietZone(v int) *QrcodeCreate {
	_c.mutation.SetQuietZone(v)
	return _c
}

// SetNillableQuietZone sets the "quiet_zone" field if the given value is not nil.
func (_c *QrcodeCreate) SetNillableQuietZone(v *int) *QrcodeCreate {
	if v != nil {
		_c.SetQuietZone(*v)
	}
	return _c
}

// Mutation returns the QrcodeMutation object of the builder.
func (_c *QrcodeCreate) Mutation() *QrcodeMutation {
	return _c.mutation
}

// Save creates the Qrcode in the database.
func (_c *QrcodeCreate) Save(ctx context.Context) (*Qrcode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QrcodeCreate) SaveX(ctx context.Context) *Qrcode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QrcodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QrcodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QrcodeCreate) defaults() {
	if _, ok := _c.mutation.Mode(); !ok {
		v := qrcode.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.WifiSsid(); !ok {
		v := qrcode.DefaultWifiSsid
		_c.mutation.SetWifiSsid(v)
	}
	if _, ok := _c.mutation.WifiPassword(); !ok {
		v := qrcode.DefaultWifiPassword
		_c.mutation.SetWifiPassword(v)
	}
	if _, ok := _c.mutation.WifiAuth(); !ok {
		v := qrcode.DefaultWifiAuth
		_c.mutation.SetWifiAuth(v)
	}
	if _, ok := _c.mutation.Caption(); !ok {
		v := qrcode.DefaultCaption
		_c.mutation.SetCaption(v)
	}
	if _, ok := _c.mutation.ErrorCorrection(); !ok {
		v := qrcode.DefaultErrorCorrection
		_c.mutation.SetErrorCorrection(v)
	}
	if _, ok := _c.mutation.QuietZone(); !ok {
		v := qrcode.DefaultQuietZone
		_c.mutation.SetQuietZone(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QrcodeCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Qrcode.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := qrcode.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Qrcode.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Qrcode.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := qrcode.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Qrcode.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WifiSsid(); !ok {
		return &ValidationError{Name: "wifi_ssid", err: errors.New(`ent: missing required field "Qrcode.wifi_ssid"`)}
	}
	if v, ok := _c.mutation.WifiSsid(); ok {
		if err := qrcode.WifiSsidValidator(v); err != nil {
			return &ValidationError{Name: "wifi_ssid", err: fmt.Errorf(`ent: validator failed for field "Qrcode.wifi_ssid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WifiPassword(); !ok {
		return &ValidationError{Name: "wifi_password", err: errors.New(`ent: missing required field "Qrcode.wifi_password"`)}
	}
	if _, ok := _c.mutation.WifiAuth(); !ok {
		return &ValidationError{Name: "wifi_auth", err: errors.New(`ent: missing required field "Qrcode.wifi_auth"`)}
	}
	if v, ok := _c.mutation.WifiAuth(); ok {
		if err := qrcode.WifiAuthValidator(v); err != nil {
			return &ValidationError{Name: "wifi_auth", err: fmt.Errorf(`ent: validator failed for field "Qrcode.wifi_auth": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Caption(); !ok {
		return &ValidationError{Name: "caption", err: errors.New(`ent: missing required field "Qrcode.caption"`)}
	}
	if v, ok := _c.mutation.Caption(); ok {
		if err := qrcode.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "Qrcode.caption": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorCorrection(); !ok {
		return &ValidationError{Name: "error_correction", err: errors.New(`ent: missing required field "Qrcode.error_correction"`)}
	}
	if v, ok := _c.mutation.ErrorCorrection(); ok {
		if err := qrcode.ErrorCorrectionValidator(v); err != nil {
			return &ValidationError{Name: "error_correction", err: fmt.Errorf(`ent: validator failed for field "Qrcode.error_correction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuietZone(); !ok {
		return &ValidationError{Name: "quiet_zone", err: errors.New(`ent: missing required field "Qrcode.quiet_zone"`)}
	}
	if v, ok := _c.mutation.QuietZone(); ok {
		if err := qrcode.QuietZoneValidator(v); err != nil {
			return &ValidationError{Name: "quiet_zone", err: fmt.Errorf(`ent: validator failed for field "Qrcode.quiet_zone": %w`, err)}
		}
	}
	return nil
}

func (_c *QrcodeCreate) sqlSave(ctx context.Context) (*Qrcode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QrcodeCreate) createSpec() (*Qrcode, *sqlgraph.CreateSpec) {
	var (
		_node = &Qrcode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(qrcode.Table, sqlgraph.NewFieldSpec(qrcode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(qrcode.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(qrcode.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.WifiSsid(); ok {
		_spec.SetField(qrcode.FieldWifiSsid, field.TypeString, value)
		_node.WifiSsid = value
	}
	if value, ok := _c.mutation.WifiPassword(); ok {
		_spec.SetField(qrcode.FieldWifiPassword, field.TypeString, value)
		_node.WifiPassword = value
	}
	if value, ok := _c.mutation.WifiAuth(); ok {
		_spec.SetField(qrcode.FieldWifiAuth, field.TypeEnum, value)
		_node.WifiAuth = value
	}
	if value, ok := _c.mutation.Caption(); ok {
		_spec.SetField(qrcode.FieldCaption, field.TypeString, value)
		_node.Caption = value
	}
	if value, ok := _c.mutation.ErrorCorrection(); ok {
		_spec.SetField(qrcode.FieldErrorCorrection, field.TypeEnum, value)
		_node.ErrorCorrection = value
	}
	if value, ok := _c.mutation.QuietZone(); ok {
		_spec.SetField(qrcode.FieldQuietZone, field.TypeInt, value)
		_node.QuietZone = value
	}
	return _node, _spec
}

// QrcodeCreateBulk is the builder for creating many Qrcode entities in bulk.
type QrcodeCreateBulk struct {
	config
	err      error
	builders []*QrcodeCreate
}

// Save creates the Qrcode entities in the database.
func (_c *QrcodeCreateBulk) Save(ctx context.Context) ([]*Qrcode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Qrcode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QrcodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QrcodeCreateBulk) SaveX(ctx context.Context) []*Qrcode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QrcodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QrcodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
