// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/sabnzbd"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Sabnzbd is the model entity for the Sabnzbd schema.
type Sabnzbd struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SABnzbd API key (apikey query parameter)
	Token string `json:"token,omitempty"`
	// SABnzbd base URL
	URL                      string `json:"url,omitempty"`
	general_settings_sabnzbd *int
	selectValues             sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sabnzbd) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sabnzbd.FieldID:
			values[i] = new(sql.NullInt64)
		case sabnzbd.FieldToken, sabnzbd.FieldURL:
			values[i] = new(sql.NullString)
		case sabnzbd.ForeignKeys[0]: // general_settings_sabnzbd
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sabnzbd fields.
func (_m *Sabnzbd) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sabnzbd.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sabnzbd.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case sabnzbd.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case sabnzbd.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field general_settings_sabnzbd", value)
			} else if value.Valid {
				_m.general_settings_sabnzbd = new(int)
				*_m.general_settings_sabnzbd = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sabnzbd.
// This includes values selected through modifiers, order, etc.
func (_m *Sabnzbd) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Sabnzbd.
// Note that you need to call Sabnzbd.Unwrap() before calling this method if this Sabnzbd
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sabnzbd) Update() *SabnzbdUpdateOne {
	return NewSabnzbdClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sabnzbd entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sabnzbd) Unwrap() *Sabnzbd {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sabnzbd is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sabnzbd) String() string {
	var builder strings.Builder
	builder.WriteString("Sabnzbd(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteByte(')')
	return builder.String()
}

// Sabnzbds is a parsable slice of Sabnzbd.
type Sabnzbds []*Sabnzbd
