// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/predicate"
	"ledit/ent/sabnzbd"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SabnzbdUpdate is the builder for updating Sabnzbd entities.
type SabnzbdUpdate struct {
	config
	hooks    []Hook
	mutation *SabnzbdMutation
}

// Where appends a list predicates to the SabnzbdUpdate builder.
func (_u *SabnzbdUpdate) Where(ps ...predicate.Sabnzbd) *SabnzbdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *SabnzbdUpdate) SetToken(v string) *SabnzbdUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SabnzbdUpdate) SetNillableToken(v *string) *SabnzbdUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SabnzbdUpdate) SetURL(v string) *SabnzbdUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SabnzbdUpdate) SetNillableURL(v *string) *SabnzbdUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the SabnzbdMutation object of the builder.
func (_u *SabnzbdUpdate) Mutation() *SabnzbdMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SabnzbdUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SabnzbdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SabnzbdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SabnzbdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SabnzbdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sabnzbd.Table, sabnzbd.Columns, sqlgraph.NewFieldSpec(sabnzbd.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sabnzbd.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(sabnzbd.FieldURL, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sabnzbd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SabnzbdUpdateOne is the builder for updating a single Sabnzbd entity.
type SabnzbdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SabnzbdMutation
}

// SetToken sets the "token" field.
func (_u *SabnzbdUpdateOne) SetToken(v string) *SabnzbdUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SabnzbdUpdateOne) SetNillableToken(v *string) *SabnzbdUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SabnzbdUpdateOne) SetURL(v string) *SabnzbdUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SabnzbdUpdateOne) SetNillableURL(v *string) *SabnzbdUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the SabnzbdMutation object of the builder.
func (_u *SabnzbdUpdateOne) Mutation() *SabnzbdMutation {
	return _u.mutation
}

// Where appends a list predicates to the SabnzbdUpdate builder.
func (_u *SabnzbdUpdateOne) Where(ps ...predicate.Sabnzbd) *SabnzbdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SabnzbdUpdateOne) Select(field string, fields ...string) *SabnzbdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sabnzbd entity.
func (_u *SabnzbdUpdateOne) Save(ctx context.Context) (*Sabnzbd, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SabnzbdUpdateOne) SaveX(ctx context.Context) *Sabnzbd {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SabnzbdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SabnzbdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SabnzbdUpdateOne) sqlSave(ctx context.Context) (_node *Sabnzbd, err error) {
	_spec := sqlgraph.NewUpdateSpec(sabnzbd.Table, sabnzbd.Columns, sqlgraph.NewFieldSpec(sabnzbd.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sabnzbd.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sabnzbd.FieldID)
		for _, f := range fields {
			if !sabnzbd.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sabnzbd.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sabnzbd.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(sabnzbd.FieldURL, field.TypeString, value)
	}
	_node = &Sabnzbd{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sabnzbd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
