// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/generalsettings"
	"ledit/ent/scene"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SceneCreate is the builder for creating a Scene entity.
type SceneCreate struct {
	config
	mutation *SceneMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SceneCreate) SetName(v string) *SceneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SceneCreate) SetEnabled(v bool) *SceneCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SceneCreate) SetNillableEnabled(v *bool) *SceneCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTriggers sets the "triggers" field.
func (_c *SceneCreate) SetTriggers(v string) *SceneCreate {
	_c.mutation.SetTriggers(v)
	return _c
}

// SetNillableTriggers sets the "triggers" field if the given value is not nil.
func (_c *SceneCreate) SetNillableTriggers(v *string) *SceneCreate {
	if v != nil {
		_c.SetTriggers(*v)
	}
	return _c
}

// SetActions sets the "actions" field.
func (_c *SceneCreate) SetActions(v string) *SceneCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetNillableActions sets the "actions" field if the given value is not nil.
func (_c *SceneCreate) SetNillableActions(v *string) *SceneCreate {
	if v != nil {
		_c.SetActions(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SceneCreate) SetPriority(v int) *SceneCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SceneCreate) SetNillablePriority(v *int) *SceneCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetTTLSeconds sets the "ttl_seconds" field.
func (_c *SceneCreate) SetTTLSeconds(v int) *SceneCreate {
	_c.mutation.SetTTLSeconds(v)
	return _c
}

// SetNillableTTLSeconds sets the "ttl_seconds" field if the given value is not nil.
func (_c *SceneCreate) SetNillableTTLSeconds(v *int) *SceneCreate {
	if v != nil {
		_c.SetTTLSeconds(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SceneCreate) SetCreatedAt(v time.Time) *SceneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SceneCreate) SetNillableCreatedAt(v *time.Time) *SceneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SceneCreate) SetUpdatedAt(v time.Time) *SceneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SceneCreate) SetNillableUpdatedAt(v *time.Time) *SceneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGeneralSettingsID sets the "general_settings" edge to the GeneralSettings entity by ID.
func (_c *SceneCreate) SetGeneralSettingsID(id int) *SceneCreate {
	_c.mutation.SetGeneralSettingsID(id)
	return _c
}

// SetNillableGeneralSettingsID sets the "general_settings" edge to the GeneralSettings entity by ID if the given value is not nil.
func (_c *SceneCreate) SetNillableGeneralSettingsID(id *int) *SceneCreate {
	if id != nil {
		_c = _c.SetGeneralSettingsID(*id)
	}
	return _c
}

// SetGeneralSettings sets the "general_settings" edge to the GeneralSettings entity.
func (_c *SceneCreate) SetGeneralSettings(v *GeneralSettings) *SceneCreate {
	return _c.SetGeneralSettingsID(v.ID)
}

// Mutation returns the SceneMutation object of the builder.
func (_c *SceneCreate) Mutation() *SceneMutation {
	return _c.mutation
}

// Save creates the Scene in the database.
func (_c *SceneCreate) Save(ctx context.Context) (*Scene, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SceneCreate) SaveX(ctx context.Context) *Scene {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SceneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SceneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SceneCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := scene.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Triggers(); !ok {
		v := scene.DefaultTriggers
		_c.mutation.SetTriggers(v)
	}
	if _, ok := _c.mutation.Actions(); !ok {
		v := scene.DefaultActions
		_c.mutation.SetActions(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := scene.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scene.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := scene.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SceneCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Scene.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := scene.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scene.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Scene.enabled"`)}
	}
	if _, ok := _c.mutation.Triggers(); !ok {
		return &ValidationError{Name: "triggers", err: errors.New(`ent: missing required field "Scene.triggers"`)}
	}
	if _, ok := _c.mutation.Actions(); !ok {
		return &ValidationError{Name: "actions", err: errors.New(`ent: missing required field "Scene.actions"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Scene.priority"`)}
	}
	if v, ok := _c.mutation.TTLSeconds(); ok {
		if err := scene.TTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "Scene.ttl_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Scene.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Scene.updated_at"`)}
	}
	return nil
}

func (_c *SceneCreate) sqlSave(ctx context.Context) (*Scene, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SceneCreate) createSpec() (*Scene, *sqlgraph.CreateSpec) {
	var (
		_node = &Scene{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scene.Table, sqlgraph.NewFieldSpec(scene.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(scene.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(scene.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Triggers(); ok {
		_spec.SetField(scene.FieldTriggers, field.TypeString, value)
		_node.Triggers = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(scene.FieldActions, field.TypeString, value)
		_node.Actions = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(scene.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.TTLSeconds(); ok {
		_spec.SetField(scene.FieldTTLSeconds, field.TypeInt, value)
		_node.TTLSeconds = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scene.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(scene.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GeneralSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scene.GeneralSettingsTable,
			Columns: []string{scene.GeneralSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generalsettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.general_settings_scenes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SceneCreateBulk is the builder for creating many Scene entities in bulk.
type SceneCreateBulk struct {
	config
	err      error
	builders []*SceneCreate
}

// Save creates the Scene entities in the database.
func (_c *SceneCreateBulk) Save(ctx context.Context) ([]*Scene, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Scene, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SceneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SceneCreateBulk) SaveX(ctx context.Context) []*Scene {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SceneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SceneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
