// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/predicate"
	"ledit/ent/sunmoon"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SunMoonUpdate is the builder for updating SunMoon entities.
type SunMoonUpdate struct {
	config
	hooks    []Hook
	mutation *SunMoonMutation
}

// Where appends a list predicates to the SunMoonUpdate builder.
func (_u *SunMoonUpdate) Where(ps ...predicate.SunMoon) *SunMoonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *SunMoonUpdate) SetToken(v string) *SunMoonUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SunMoonUpdate) SetNillableToken(v *string) *SunMoonUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SunMoonUpdate) SetURL(v string) *SunMoonUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SunMoonUpdate) SetNillableURL(v *string) *SunMoonUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the SunMoonMutation object of the builder.
func (_u *SunMoonUpdate) Mutation() *SunMoonMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SunMoonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SunMoonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SunMoonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SunMoonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SunMoonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sunmoon.Table, sunmoon.Columns, sqlgraph.NewFieldSpec(sunmoon.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sunmoon.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(sunmoon.FieldURL, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sunmoon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SunMoonUpdateOne is the builder for updating a single SunMoon entity.
type SunMoonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SunMoonMutation
}

// SetToken sets the "token" field.
func (_u *SunMoonUpdateOne) SetToken(v string) *SunMoonUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SunMoonUpdateOne) SetNillableToken(v *string) *SunMoonUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SunMoonUpdateOne) SetURL(v string) *SunMoonUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SunMoonUpdateOne) SetNillableURL(v *string) *SunMoonUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// Mutation returns the SunMoonMutation object of the builder.
func (_u *SunMoonUpdateOne) Mutation() *SunMoonMutation {
	return _u.mutation
}

// Where appends a list predicates to the SunMoonUpdate builder.
func (_u *SunMoonUpdateOne) Where(ps ...predicate.SunMoon) *SunMoonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SunMoonUpdateOne) Select(field string, fields ...string) *SunMoonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SunMoon entity.
func (_u *SunMoonUpdateOne) Save(ctx context.Context) (*SunMoon, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SunMoonUpdateOne) SaveX(ctx context.Context) *SunMoon {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SunMoonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SunMoonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SunMoonUpdateOne) sqlSave(ctx context.Context) (_node *SunMoon, err error) {
	_spec := sqlgraph.NewUpdateSpec(sunmoon.Table, sunmoon.Columns, sqlgraph.NewFieldSpec(sunmoon.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SunMoon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sunmoon.FieldID)
		for _, f := range fields {
			if !sunmoon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sunmoon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sunmoon.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(sunmoon.FieldURL, field.TypeString, value)
	}
	_node = &SunMoon{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sunmoon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
