// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/predicate"
	"ledit/ent/timelapseframe"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimelapseFrameUpdate is the builder for updating TimelapseFrame entities.
type TimelapseFrameUpdate struct {
	config
	hooks    []Hook
	mutation *TimelapseFrameMutation
}

// Where appends a list predicates to the TimelapseFrameUpdate builder.
func (_u *TimelapseFrameUpdate) Where(ps ...predicate.TimelapseFrame) *TimelapseFrameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *TimelapseFrameUpdate) SetDeviceID(v int) *TimelapseFrameUpdate {
	_u.mutation.ResetDeviceID()
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableDeviceID(v *int) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// AddDeviceID adds value to the "device_id" field.
func (_u *TimelapseFrameUpdate) AddDeviceID(v int) *TimelapseFrameUpdate {
	_u.mutation.AddDeviceID(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *TimelapseFrameUpdate) SetCapturedAt(v time.Time) *TimelapseFrameUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableCapturedAt(v *time.Time) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *TimelapseFrameUpdate) SetSourceType(v string) *TimelapseFrameUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableSourceType(v *string) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *TimelapseFrameUpdate) SetSourceID(v int) *TimelapseFrameUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableSourceID(v *int) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *TimelapseFrameUpdate) AddSourceID(v int) *TimelapseFrameUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *TimelapseFrameUpdate) SetSourceLabel(v string) *TimelapseFrameUpdate {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableSourceLabel(v *string) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *TimelapseFrameUpdate) SetFilePath(v string) *TimelapseFrameUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableFilePath(v *string) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *TimelapseFrameUpdate) SetWidth(v int) *TimelapseFrameUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableWidth(v *int) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *TimelapseFrameUpdate) AddWidth(v int) *TimelapseFrameUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *TimelapseFrameUpdate) SetHeight(v int) *TimelapseFrameUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *TimelapseFrameUpdate) SetNillableHeight(v *int) *TimelapseFrameUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *TimelapseFrameUpdate) AddHeight(v int) *TimelapseFrameUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// Mutation returns the TimelapseFrameMutation object of the builder.
func (_u *TimelapseFrameUpdate) Mutation() *TimelapseFrameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimelapseFrameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimelapseFrameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimelapseFrameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimelapseFrameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TimelapseFrameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(timelapseframe.Table, timelapseframe.Columns, sqlgraph.NewFieldSpec(timelapseframe.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(timelapseframe.FieldDeviceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeviceID(); ok {
		_spec.AddField(timelapseframe.FieldDeviceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(timelapseframe.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(timelapseframe.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(timelapseframe.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(timelapseframe.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(timelapseframe.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(timelapseframe.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(timelapseframe.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(timelapseframe.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(timelapseframe.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(timelapseframe.FieldHeight, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timelapseframe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimelapseFrameUpdateOne is the builder for updating a single TimelapseFrame entity.
type TimelapseFrameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TimelapseFrameMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *TimelapseFrameUpdateOne) SetDeviceID(v int) *TimelapseFrameUpdateOne {
	_u.mutation.ResetDeviceID()
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableDeviceID(v *int) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// AddDeviceID adds value to the "device_id" field.
func (_u *TimelapseFrameUpdateOne) AddDeviceID(v int) *TimelapseFrameUpdateOne {
	_u.mutation.AddDeviceID(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *TimelapseFrameUpdateOne) SetCapturedAt(v time.Time) *TimelapseFrameUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableCapturedAt(v *time.Time) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *TimelapseFrameUpdateOne) SetSourceType(v string) *TimelapseFrameUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableSourceType(v *string) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *TimelapseFrameUpdateOne) SetSourceID(v int) *TimelapseFrameUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableSourceID(v *int) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *TimelapseFrameUpdateOne) AddSourceID(v int) *TimelapseFrameUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *TimelapseFrameUpdateOne) SetSourceLabel(v string) *TimelapseFrameUpdateOne {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableSourceLabel(v *string) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *TimelapseFrameUpdateOne) SetFilePath(v string) *TimelapseFrameUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableFilePath(v *string) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *TimelapseFrameUpdateOne) SetWidth(v int) *TimelapseFrameUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableWidth(v *int) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *TimelapseFrameUpdateOne) AddWidth(v int) *TimelapseFrameUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *TimelapseFrameUpdateOne) SetHeight(v int) *TimelapseFrameUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *TimelapseFrameUpdateOne) SetNillableHeight(v *int) *TimelapseFrameUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *TimelapseFrameUpdateOne) AddHeight(v int) *TimelapseFrameUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// Mutation returns the TimelapseFrameMutation object of the builder.
func (_u *TimelapseFrameUpdateOne) Mutation() *TimelapseFrameMutation {
	return _u.mutation
}

// Where appends a list predicates to the TimelapseFrameUpdate builder.
func (_u *TimelapseFrameUpdateOne) Where(ps ...predicate.TimelapseFrame) *TimelapseFrameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimelapseFrameUpdateOne) Select(field string, fields ...string) *TimelapseFrameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TimelapseFrame entity.
func (_u *TimelapseFrameUpdateOne) Save(ctx context.Context) (*TimelapseFrame, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimelapseFrameUpdateOne) SaveX(ctx context.Context) *TimelapseFrame {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimelapseFrameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimelapseFrameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TimelapseFrameUpdateOne) sqlSave(ctx context.Context) (_node *TimelapseFrame, err error) {
	_spec := sqlgraph.NewUpdateSpec(timelapseframe.Table, timelapseframe.Columns, sqlgraph.NewFieldSpec(timelapseframe.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TimelapseFrame.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timelapseframe.FieldID)
		for _, f := range fields {
			if !timelapseframe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timelapseframe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(timelapseframe.FieldDeviceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeviceID(); ok {
		_spec.AddField(timelapseframe.FieldDeviceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(timelapseframe.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(timelapseframe.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(timelapseframe.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(timelapseframe.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(timelapseframe.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(timelapseframe.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(timelapseframe.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(timelapseframe.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(timelapseframe.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(timelapseframe.FieldHeight, field.TypeInt, value)
	}
	_node = &TimelapseFrame{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timelapseframe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
