// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ledit/ent/timelapseframe"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimelapseFrameCreate is the builder for creating a TimelapseFrame entity.
type TimelapseFrameCreate struct {
	config
	mutation *TimelapseFrameMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *TimelapseFrameCreate) SetDeviceID(v int) *TimelapseFrameCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *TimelapseFrameCreate) SetCapturedAt(v time.Time) *TimelapseFrameCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *TimelapseFrameCreate) SetNillableCapturedAt(v *time.Time) *TimelapseFrameCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *TimelapseFrameCreate) SetSourceType(v string) *TimelapseFrameCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *TimelapseFrameCreate) SetSourceID(v int) *TimelapseFrameCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetSourceLabel sets the "source_label" field.
func (_c *TimelapseFrameCreate) SetSourceLabel(v string) *TimelapseFrameCreate {
	_c.mutation.SetSourceLabel(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *TimelapseFrameCreate) SetFilePath(v string) *TimelapseFrameCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *TimelapseFrameCreate) SetWidth(v int) *TimelapseFrameCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *TimelapseFrameCreate) SetHeight(v int) *TimelapseFrameCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimelapseFrameCreate) SetCreatedAt(v time.Time) *TimelapseFrameCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimelapseFrameCreate) SetNillableCreatedAt(v *time.Time) *TimelapseFrameCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the TimelapseFrameMutation object of the builder.
func (_c *TimelapseFrameCreate) Mutation() *TimelapseFrameMutation {
	return _c.mutation
}

// Save creates the TimelapseFrame in the database.
func (_c *TimelapseFrameCreate) Save(ctx context.Context) (*TimelapseFrame, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimelapseFrameCreate) SaveX(ctx context.Context) *TimelapseFrame {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimelapseFrameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimelapseFrameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimelapseFrameCreate) defaults() {
	if _, ok := _c.mutation.CapturedAt(); !ok {
		v := timelapseframe.DefaultCapturedAt()
		_c.mutation.SetCapturedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := timelapseframe.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimelapseFrameCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "TimelapseFrame.device_id"`)}
	}
	if _, ok := _c.mutation.CapturedAt(); !ok {
		return &ValidationError{Name: "captured_at", err: errors.New(`ent: missing required field "TimelapseFrame.captured_at"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "TimelapseFrame.source_type"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "TimelapseFrame.source_id"`)}
	}
	if _, ok := _c.mutation.SourceLabel(); !ok {
		return &ValidationError{Name: "source_label", err: errors.New(`ent: missing required field "TimelapseFrame.source_label"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "TimelapseFrame.file_path"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "TimelapseFrame.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "TimelapseFrame.height"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TimelapseFrame.created_at"`)}
	}
	return nil
}

func (_c *TimelapseFrameCreate) sqlSave(ctx context.Context) (*TimelapseFrame, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimelapseFrameCreate) createSpec() (*TimelapseFrame, *sqlgraph.CreateSpec) {
	var (
		_node = &TimelapseFrame{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timelapseframe.Table, sqlgraph.NewFieldSpec(timelapseframe.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(timelapseframe.FieldDeviceID, field.TypeInt, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(timelapseframe.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(timelapseframe.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(timelapseframe.FieldSourceID, field.TypeInt, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.SourceLabel(); ok {
		_spec.SetField(timelapseframe.FieldSourceLabel, field.TypeString, value)
		_node.SourceLabel = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(timelapseframe.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(timelapseframe.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(timelapseframe.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timelapseframe.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TimelapseFrameCreateBulk is the builder for creating many TimelapseFrame entities in bulk.
type TimelapseFrameCreateBulk struct {
	config
	err      error
	builders []*TimelapseFrameCreate
}

// Save creates the TimelapseFrame entities in the database.
func (_c *TimelapseFrameCreateBulk) Save(ctx context.Context) ([]*TimelapseFrame, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TimelapseFrame, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimelapseFrameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimelapseFrameCreateBulk) SaveX(ctx context.Context) []*TimelapseFrame {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimelapseFrameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimelapseFrameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
