// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ledit/ent/webhooksettings"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WebhookSettings is the model entity for the WebhookSettings schema.
type WebhookSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// DefaultTTL holds the value of the "default_ttl" field.
	DefaultTTL                       int `json:"default_ttl,omitempty"`
	general_settings_webhooksettings *int
	selectValues                     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhooksettings.FieldID, webhooksettings.FieldDefaultTTL:
			values[i] = new(sql.NullInt64)
		case webhooksettings.FieldAPIKey:
			values[i] = new(sql.NullString)
		case webhooksettings.ForeignKeys[0]: // general_settings_webhooksettings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookSettings fields.
func (_m *WebhookSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhooksettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case webhooksettings.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case webhooksettings.FieldDefaultTTL:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_ttl", values[i])
			} else if value.Valid {
				_m.DefaultTTL = int(value.Int64)
			}
		case webhooksettings.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field general_settings_webhooksettings", value)
			} else if value.Valid {
				_m.general_settings_webhooksettings = new(int)
				*_m.general_settings_webhooksettings = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookSettings.
// This includes values selected through modifiers, order, etc.
func (_m *WebhookSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookSettings.
// Note that you need to call WebhookSettings.Unwrap() before calling this method if this WebhookSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebhookSettings) Update() *WebhookSettingsUpdateOne {
	return NewWebhookSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebhookSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebhookSettings) Unwrap() *WebhookSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebhookSettings) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("api_key=")
	builder.WriteString(_m.APIKey)
	builder.WriteString(", ")
	builder.WriteString("default_ttl=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultTTL))
	builder.WriteByte(')')
	return builder.String()
}

// WebhookSettingsSlice is a parsable slice of WebhookSettings.
type WebhookSettingsSlice []*WebhookSettings
