// Code generated by ent, DO NOT EDIT.

package themeassignment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the themeassignment type in the database.
	Label = "theme_assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// EdgeTheme holds the string denoting the theme edge name in mutations.
	EdgeTheme = "theme"
	// Table holds the table name of the themeassignment in the database.
	Table = "theme_assignments"
	// ThemeTable is the table that holds the theme relation/edge.
	ThemeTable = "theme_assignments"
	// ThemeInverseTable is the table name for the Theme entity.
	// It exists in this package in order to avoid circular dependency with the "theme" package.
	ThemeInverseTable = "themes"
	// ThemeColumn is the table column denoting the theme relation/edge.
	ThemeColumn = "theme_assignments"
)

// Columns holds all SQL columns for themeassignment fields.
var Columns = []string{
	FieldID,
	FieldTargetType,
	FieldTargetID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "theme_assignments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"theme_assignments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	TargetTypeValidator func(string) error
)

// OrderOption defines the ordering options for the ThemeAssignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByThemeField orders the results by theme field.
func ByThemeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newThemeStep(), sql.OrderByField(field, opts...))
	}
}
func newThemeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ThemeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ThemeTable, ThemeColumn),
	)
}
