// Code generated by ent, DO NOT EDIT.

package pixelart

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pixelart type in the database.
	Label = "pixel_art"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGridWidth holds the string denoting the grid_width field in the database.
	FieldGridWidth = "grid_width"
	// FieldGridHeight holds the string denoting the grid_height field in the database.
	FieldGridHeight = "grid_height"
	// FieldFrames holds the string denoting the frames field in the database.
	FieldFrames = "frames"
	// FieldBindings holds the string denoting the bindings field in the database.
	FieldBindings = "bindings"
	// FieldAPIURL holds the string denoting the api_url field in the database.
	FieldAPIURL = "api_url"
	// FieldAPIToken holds the string denoting the api_token field in the database.
	FieldAPIToken = "api_token"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIsDraft holds the string denoting the is_draft field in the database.
	FieldIsDraft = "is_draft"
	// Table holds the table name of the pixelart in the database.
	Table = "pixel_arts"
)

// Columns holds all SQL columns for pixelart fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldGridWidth,
	FieldGridHeight,
	FieldFrames,
	FieldBindings,
	FieldAPIURL,
	FieldAPIToken,
	FieldEnabled,
	FieldIsDraft,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pixel_arts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"general_settings_pixel_arts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGridWidth holds the default value on creation for the "grid_width" field.
	DefaultGridWidth int
	// DefaultGridHeight holds the default value on creation for the "grid_height" field.
	DefaultGridHeight int
	// DefaultFrames holds the default value on creation for the "frames" field.
	DefaultFrames string
	// DefaultBindings holds the default value on creation for the "bindings" field.
	DefaultBindings string
	// DefaultAPIURL holds the default value on creation for the "api_url" field.
	DefaultAPIURL string
	// DefaultAPIToken holds the default value on creation for the "api_token" field.
	DefaultAPIToken string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultIsDraft holds the default value on creation for the "is_draft" field.
	DefaultIsDraft bool
)

// OrderOption defines the ordering options for the PixelArt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGridWidth orders the results by the grid_width field.
func ByGridWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGridWidth, opts...).ToFunc()
}

// ByGridHeight orders the results by the grid_height field.
func ByGridHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGridHeight, opts...).ToFunc()
}

// ByFrames orders the results by the frames field.
func ByFrames(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrames, opts...).ToFunc()
}

// ByBindings orders the results by the bindings field.
func ByBindings(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindings, opts...).ToFunc()
}

// ByAPIURL orders the results by the api_url field.
func ByAPIURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIURL, opts...).ToFunc()
}

// ByAPIToken orders the results by the api_token field.
func ByAPIToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIToken, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIsDraft orders the results by the is_draft field.
func ByIsDraft(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDraft, opts...).ToFunc()
}
