# Generated by Django 5.0.4 on 2024-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="random",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="f1",
            field=models.ManyToManyField(blank=True, to="ledit.f1"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="homeassitant",
            field=models.ManyToManyField(blank=True, to="ledit.homeassistant"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="images",
            field=models.ManyToManyField(blank=True, to="ledit.image"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="lidarr",
            field=models.ManyToManyField(blank=True, to="ledit.lidarr"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="radarr",
            field=models.ManyToManyField(blank=True, to="ledit.radarr"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="readarr",
            field=models.ManyToManyField(blank=True, to="ledit.readarr"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="sonarr",
            field=models.ManyToManyField(blank=True, to="ledit.sonarr"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="stocks_tracker",
            field=models.ManyToManyField(blank=True, to="ledit.stockstracker"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="untapped",
            field=models.ManyToManyField(blank=True, to="ledit.untapped"),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="wheater",
            field=models.ManyToManyField(blank=True, to="ledit.weather"),
        ),
    ]
