# Generated by Django 5.1.7 on 2025-03-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledit', '0004_video_generalsettings_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CyrptoTracker',
        ),
        migrations.DeleteModel(
            name='DeviceSettings',
        ),
        migrations.DeleteModel(
            name='Ical',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='lidarr',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='readarr',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='stocks_tracker',
        ),
        migrations.DeleteModel(
            name='Lidarr',
        ),
        migrations.DeleteModel(
            name='Readarr',
        ),
        migrations.DeleteModel(
            name='StocksTracker',
        ),
    ]
