# Generated by Django 5.0.4 on 2024-04-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("port", models.IntegerField(default="6270")),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("width", models.IntegerField(default="64")),
                ("height", models.IntegerField(default="64")),
            ],
        ),
        migrations.CreateModel(
            name="F1Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HomeAssistantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="", upload_to="custom_images")),
            ],
        ),
        migrations.CreateModel(
            name="RadarrSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SonarrSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StocksTrackerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UntappedSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeout", models.FloatField(max_length=10)),
                (
                    "f1",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.f1settings",
                    ),
                ),
                (
                    "homeassitant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.homeassistantsettings",
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ledit.image"
                    ),
                ),
                (
                    "radarr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.radarrsettings",
                    ),
                ),
                (
                    "sonarr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.sonarrsettings",
                    ),
                ),
                (
                    "stocks_tracker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.stockstrackersettings",
                    ),
                ),
                (
                    "untapped",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.untappedsettings",
                    ),
                ),
                (
                    "wheater",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledit.weathersettings",
                    ),
                ),
            ],
        ),
    ]
