# Generated by Django 5.0.4 on 2024-04-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledit", "0002_delete_sitesettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LEDitSettings",
            new_name="GeneralSettings",
        ),
    ]
